---
title: "GES 001 経済と経済学"
author: "H. Suzuki"
date: "`r Sys.Date()`"
output:
  html_notebook: default
---

> 2023年12月2日に海蔵寺さんからいただいた文書をもとに作成。リンクを知っている者は、だれでも見ることが可能であるが、学生用は別途作成。

## **このコースについて**

### スケジュール・担当教員・教室

3/TU, 2/TH, 3/TH　

担当教員：海蔵寺大成

場所：2，3/TH 本館H260　３/TU ILC106

Moodle：[Link](https://2023.moodle.icu.ac.jp/course/view.php?id=1440)

### 概要

現在、我々は先の見えない不確実な時代を生きている。現代社会には、多様な問題が山積している。これらの問題の多くは、資本主義経済のメカニズムが必然的に作り出す問題と関係している。冬学期の「経済と経済学」では、資本主義経済下で起きている問題のうち、富の不平等と貧困、気候変動、戦争・紛争を取り上げ、国際機関のレポートと世界銀行が公表しているデータ（World Development Indicators （WDI））を利用して現状を概観し、解決策について議論する。

### 授業形式

対面形式で行います。

木曜日は本館でスライドを用いた講義を本館講義室で行う。火曜日（3時限目）は、世界銀行のデータを使ったデータサイエンスの基礎を学び、実際のデータを分析する基礎的な方法を演習を通じて学ぶ予定である。データ分析ソフトとしてRとRStudioを使う。火曜日の演習はILC-106で行う予定である。

データサイエンス演習の目的は次の２つである。

1.  国際機関が公表しているデータベースからデータを収集し、自由に利用できる基本的なスキルを身に着ける。
2.  講義で学習した内容に関連するデータを世界的なレベルで調べてみる。問題を「世界ごと」として考える視点を養う。
3.  WDIの関連するデータを調査することで、「自分なりの問い」を持てるようになる。

### 火曜日の演習

鈴木寛先生（ICU名誉教授、数学）を講師としてお招きして、Rを使って世界経済のデータベース（World Development Indicators (WDI)）を収集、整理し、各種のグラフを作成したり、モデル化する方法を演習を通して学習する。WDIは、講義で扱う世界的な社会問題を実際のデータを見ることで理解できる貴重なデータベースである。

この講義期間に、学生の皆さんに講義部分で扱う、貧困、気候変動、紛争などの世界的なデータに触れることで、Rという便利なツールを知ってもらい、期末レポートの作成に役立ててほしいと考えている。

#### データ [[Link](https://ds-sl.github.io/intro2r/ges001/ges001data.nb.html)]

### コメントの提出

開講日中（23：59まで）にコメントを提出してください。コメントには、講義の内容に関するコメント、質問を書いてください。講義への参加としてカウントしています。

### 資料

毎週講義で使用するスライドと資料のPDFをアップロードします。各自、Moodleサイトからダウンロードしてください。

火曜日の演習の資料は、この[ページ](https://ds-sl.github.io/intro2r/ges001/index.html) を参照してください。左のページを、Moodle にリンクをつけて、学生に公開。現在のページと、そこから、準備とあるページは、教員用。

## **スケジュール**

### 第1週

12/07(TH)　イントロダクション: 市場の失敗とSDGs 1

　　　　　 　　市場の失敗とSDGs 2

資本主義経済が引き起こす問題：不平等の拡大、気候変動などとSDGｓが提案された理由を簡単に講義します。

#### メモ

稲葉先生は、冬学期から特別研究期間で海蔵寺先生ひとりで担当

-   富の不平等と貧困

-   気候変動：南の方では、より深刻

-   戦争・紛争：ウクライナとロシア、パレスチナとイスラエル

正解があるというよりも、みなで考えたい。

データを見て考えられること

-   実態の状況をみる

-   国際機関などのレポートの図表ではなく、データそのものを見てほしい

12/12(TU)　Rでデータサイエンス１：導入 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-1.nb.html)]・ [[スライド](https://ds-sl.github.io/intro2r/ges001/ges00100.html)]・[[RNotebook](https://ds-sl.github.io/intro2r/ges001/ges00100.nb.html)]・[[Video](https://youtu.be/pT3690JKjp0)]変更期間です。次週から参加する学生がいることを想定する必要があります。RとRStudioのインストールやRを使うことのメリット、Rの簡単な使い方など。GDPを例にする。（ECO101の鈴木先生にRコード）。

#### イントロダクション：資本主義とSDGs

1700年ごろ、資本家という言葉がうまれ、資本主義ということばが生まれた

１８世紀後半、イギリスで起こった「産業革命」。 産業革命とは、この時代、生産活動の中心が「農業」から「工業」へ移ったことで生じた社会の大きな変化のことをいいます。

「セイの法則」というのは、「供給は、それ自身の需要を作り出す」というもの。

アダム・スミスの流れを汲む新古典派経済学は、国家が個々の経済主 体の経済活動に干渉しないことが望ましいと考える。

小さな政府→貧富の格差の拡大

ケインズ経済学は、政府が積極的に経済に介入することで景気変動を 抑えることを提唱する。

大きな政府→財政赤字の拡大

ピケティは、富の格差拡大の原因を「株式や土地などの資本収益率（ｒ ）が、経済成長率（ｇ）より大きい（ｒ＞ｇ）」ことに求め、先進資本主義国 で土地や株などの資産を多く持つ資本家と労働者の貧富の格差が拡 大すると主張した。（21世紀の資本：みすず書房）

#### 市場の失敗（market failure）

「外部性（externality）外の人にも影響を与える財」や「公共財（public goods）」の存在、「独占（monopoly）や寡占（oligopoly）」、「規模の経済」

正の外部性の場合、財・サービスの供給の社会的便益が考慮されない ので過少に需要される。（例：教育、対策：公的支出（義務教育など））

政府の失敗

-   外部性のある財・サービスは、政府が介入しなければ、適切に財・サ ービスの供給が行われない。しかし、様々な理由で政府が適切に公 共財を提供できない場合がある。これを「政府の失敗」という。

-   例1：地球環境の破壊は、1国が取り組むだけでは不十分で国際的な 協調が必要であるが、誰が地球環境を防ぐためのコストを支払うか をめぐって協力関係が構築できない場合がある。

-   例２：財政的に資金不足で義務教育や社会保障を政府が提供できな いことがある。

-   例３：高齢化が進行する社会では、社会保障に膨大な資金が必要に なり、教育や気候変動対策に関連する公共財の供給が犠牲にされ る場合がある。

QUIZ：貧困、気候変動、紛争は、経済問題だ？　貧困、気候変動、紛争は、経済とは関係が ない。？

SDGsの前文・宣言 国連

-   わたしたちが発表する17の目標と169のターゲットは、このアジェンダ がどれだけ広く高い目標をかかげているかを表しています。

経済学パートでは、SDGsの17の目標のうち、 「１．貧困をなくそう」 「４．質の高い教育をみんなに」 「13．気候変動に具体的な対策を」 「16.平和と公正をすべての人に」 などの目標を取り上げる。

International poverty lines

-   This paper, prepared by the World Bank Group and UNICEF, presents estimated trends in child poverty from 2013 to 2022, based on three international poverty lines:

-   \$2.15 (extreme poverty)

-   \$3.65 (lower middle income), and

-   \$6.85 (upper middle income)

-   \$1.9 (extreme poverty, after October, 2015)

-   \$1.25 (extreme poverty, before October 2015)

UNICEF [[Link](https://www.unicef.or.jp/kodomo/sdgs/17goals/9-industry/)]

1.  世界では、六人に一人（3億5600万人）の子どもたちが「極度にまずしい」暮らしをしています。

2.  40人中4日食べるものがない。

3.  すべての人に健康と福祉を：サハラ以南のアメリカでは、二人に一人のこどもが風邪で肺炎になっても、治療を受けられない。

4.  質の高い教育をみんなに：サハラ否のアフリカでは、五人に一人が小学校に通えない

5.  ジェンダー平等を実現しよう：6歳から11歳のこどものうち、一生学校に通うことができない女の子は、男の子の二倍

6.  安全な水とトイレを世界中に：水道の設備がない暮らしをしている人は22億人以上います。トイレがなく、道端や草むらなどで用をたす人、道端4億1900万人

7.  エネルギーをみんなに。そしてクリーンに：世界で電力を使えない人は七億3300万人。

8.  働きがいも、経済成長も：世界の最も国々では、5歳から17歳までのこどもの5人に一人が労働を強いられています。

9.  産業と技術革新の基盤を作ろう：世界では27億人のひとびとがインターネットにアクセスできません。特に開発の遅れている国々の農村部では、13%の人が携帯電話の電話が届かないところに暮らしています。

10. 人や国の不平等をなくそう：世界の最も豊かな1%の人が世界全体の富の約33%をもっています。

11. 住み続けられるまちづくり：

12. 作る責任、使う責任：食品の約3分の1が捨てられている

13. 気候変動に具体的な対策を：世界中で気候変動が起こっています。 過去30年間の日本の熱帯夜の平均日数は、 1910年からの30年間の平均の約2.8倍です。

14. 海野豊かさを守ろう：プラスチックゴミの年間900万トン〜1400万トン（2016年時点）、海に流れ出ています。

15. 陸の豊かさを守ろう：絶滅の危機にさらされていると推定される割合：鳥類14%、針葉樹34%、哺乳類25%、両セリ類41%（絶滅危機の推定割合）

16. 平和と公正をすべての人に：世界のどこかで5分に一人、こどもが暴力によってなくなっている。

17. パートナーシップで目標を達成しよう：国際協力がますます必要とされている一方、2018年に政府開発援助に使われたお金は、2.7%減少

### 第2週

12/14(TH)　所得と富の不平等の現状１

　　　　　  所得と富の不平等の現状２

講義では、第2週、第3週とWorld Inequality report 2022を使って、所得と富の不平等について議論します。[[wir2022](https://wir2022.wid.world/www-site/uploads/2023/03/D_FINAL_WIL_RIM_RAPPORT_2303.pdf)]

-   演習について：Questions and Comments

-   前回の授業のコメントについて

    -   極度の貧困の、１日二ドルがなにを意味するか。

    -   資本主義は、主義主張ではなく、生産様式。

    -   食品ロスなど、身近な問題にどう向き合うか。

    -   経済格差と再分配の関係性の問題。

    -   厚生経済学（Welfare Economics）

#### 所得と富の不平等

World Inequality Report 2022 [[Link](https://wir2022.wid.world)]・[[みんなのデータサイエンスへのリンク](https://icu-hsuzuki.github.io/ds4aj/wid.html#wid)]

-   執筆者：エマニュエル・ザイズ、ガブリエル・ザックマン、トマ・ピケティ

    -   The Triumph of of Injustice「つくられた格差」エマニュエル・ザイズ、ガブリエル・ザックマン [[Link](https://www.kobunsha.com/shelf/book/isbn/9784334962432)]

    -   LE CAPITAL「21世紀の資本」トマ・ピケティ [[概要](https://www.flierinc.com/summary/337)]

-   Executive Summary [[Link](https://wir2022.wid.world/executive-summary/)]

-   Introduction [[Link](https://wir2022.wid.world/introduction/)]

-   Chapter 1 Global economic inequality: insights: [[Link](https://wir2022.wid.world/chapter-1/)]

-   Chapter 2 Global inequality from 1820 to now: the persistence and mutation of extreme inequality [[Link](https://wir2022.wid.world/chapter-2/)]

-   Chapter 3 Rich countries, poor governments [[Link](https://wir2022.wid.world/chapter-3/)]

    -   Figure 3.4 [[Link](https://wir2022.wid.world/www-site/uploads/2021/10/CH3-F3.4-4.jpg)]

        -   ロシア：ウルガルヒが民営化のときの財を買い取った

-   Chapter 4 Global wealth inequality: the rise of multimillionaires [[Link](https://wir2022.wid.world/chapter-4/)]

    -   Figure 4.2 Average annual wealth growth rate [[Link](https://wir2022.wid.world/www-site/uploads/2021/10/CH4-F4.2-2.jpg)]

    -   Figure 4.4 Top 1% versus bottom 50% wealth shared in Western Europe and the US, 1910-2020 [[Link](https://wir2022.wid.world/www-site/uploads/2021/10/CH4-F4.4-3.jpg)]

    -   Figure 4.5 Top 1% wealth shared in the BRICs [[Link](https://wir2022.wid.world/www-site/uploads/2021/10/CH4-F4.5-2.jpg)]

-   Chapter 5 Half the sky? The Female Labor Income Share in a Global Perspective [[Link](https://wir2022.wid.world/chapter-5/)]

-   Chapter 6 Global carbon inequality [[Link](https://wir2022.wid.world/chapter-6/)]

-   Chapter 7 The road to redistributing wealth [[Link](https://wir2022.wid.world/chapter-7/)]

-   Chapter 8 Taxing Multinationals or Taxing Wealthy Individuals? [[Link](https://wir2022.wid.world/chapter-8/)]

-   Chapter 9 Global vs Unilateral Perspectives on Tax Justice [[Link](https://wir2022.wid.world/chapter-9/)]

-   Chapter 10 Emancipation, redistribution and sustainability [[Link](https://wir2022.wid.world/chapter-10/)]

-   Glossary Country appendix [[Link](https://wir2022.wid.world/country-appendix-glossary/)]

12/19(TU)　Rでデータサイエンス2：人口の少子高齢化　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-2.nb.html)]・ [[スライド](https://ds-sl.github.io/intro2r/ges001/ges00101.html)]・[[RNotebook](https://ds-sl.github.io/intro2r/ges001/ges00101.nb.html)]・[[ビデオ](https://youtu.be/AFNVhNdWZ_Y)]

**People- Population dynamics**

Population, total：SP.POP.TOTL

Birth rate, crude (per 1,000 people)：SP.DYN.CBRT.IN

Death rate, crude (per 1,000 people)：SP.DYN.CDRT.IN

Age dependency ratio, young (% of working-age population)：SP.POP.DPND.YG

Age dependency ratio, old (% of working-age population)：SP.POP.DPND.OL

### 第3週

12/21(TH)　不平等を無くすために何をするべきか1

　　　　　  不平等を無くすために何をするべきか2

講義では、所得の世界的格差の現状を踏まえて、高所得者に対する資産課税、金融取引税の可能性について議論します。

#### コメント・レビュー

-   PPP 購買力平価（Purchasing Power Parity）:　日本では、100円〜1USD

    -   どの地域の、富の分配がより不平等になっているか。

-   貧富の差の拡大：自動的ではなく、政治的選択、不平等は仕方がないのではないか。

-   給付金・税の軽減、一時的・中長期的

-   富と所得の違い、その影響。資産はどのように、計算するのか。

-   バイアスの克服、Infographics

-   富の格差：共産国・社会主義国、資本主義国、貧しい国（MENA: Middle East and North Africa）

#### 不平等をなくすために何をなすべきか

World Inequality Report 2022 [[Link](https://wir2022.wid.world)]

-   Chapter 5 Half the sky? The Female Labor Income Share in a Global Perspective [[Link](https://wir2022.wid.world/chapter-5/)]

    -   ジェンダーの不平等は世界レベルで依然としてかなりのものであり、国内での進展は遅すぎる

    ```         
    -   Figure 12. in Executive Sammary? Men's and Women's shares in global labor incomes, 1990-2020 [[Link](https://wir2022.wid.world/chapter-5/)]
    ```

    -   Figure 5.2 Female income share across the world, 1990-2020 [[Link](https://wir2022.wid.world/chapter-5/)]

        -   中国の格差は拡大している。

    -   Figure B5.1 <https://wir2022.wid.world/chapter-5/> UN Gender Inequality Index [[Link](https://hdr.undp.org/data-center/thematic-composite-indices/gender-inequality-index#/indicies/GII)]

    -   ほとんどの国では、1990年代以降、国民労働所得に占める女性の 割合が増加している。例外は中国と旧東欧圏の一部の国（リトアニア 、ポーランド、ロシア、スロベニア、スロバキア）で、女性の労働所得 シェアは国際比較ですでに高い水準から低下している。MENA "地 域の女性の所得シェアは15％と最も低く、旧東欧圏は41％と最も高 い。

    -   日本の男女間賃金格差

        -   男女間の教育水準の違いがなくなりつつあるが、一方で人的資本の条 件（教育水準など）をコントロールしてもなお残る男女間賃金格差（ residual gap）が存在している。

        -   子供を持つことによって所得が低下する 「Child Penalty 」が観察され 、 女性の所得減少 （=Motherhood Penalty）につながっている可能性が指 摘されている。

-   Chapter 6 Global carbon inequality [[Link](https://wir2022.wid.world/chapter-6/)]

    -   気候変動の箇所で取り扱う

-   Chapter 7 The road to redistributing wealth [[Link](https://wir2022.wid.world/chapter-7/)]

    -   富の再分配は将来に投資するための鍵

        -   世界の大富豪に対する富裕税シナリオからの税収の増加についての分析

        -   資本が富裕層の集中していることを考えると、適度な累進課税は政府に かなりの収入を生み出す可能性がある。ここで提案された適度な累進税 率のシナリオでは、世界の税収の1.6％が生み出され、教育、健康、そし て気候変動問題への取り組みに税収を再投資することが可能になる。

    -   富の不平等は分布の最も富裕な層で増加している

        -   個人資産税の近代化：アメリカ、イギリス、ドイツ、あるいは日本では、1936年から1980年の間、最高所得税率は一貫して70％以上でした。ほとんどの国が1980年以 来最高所得税率を引き下げた。

        -   固定資産税を近代化する最善の方法は、その基盤を不動産だけでなくあらゆる形態の資産に拡大し、均一税率から累進課税スケジュールに移行することである。実際には、これはフラットな固定資産税を富に対する現代の累進課税に変換することになります。

    -   世界的な累進富裕税の試算

        -   [表7.1](https://wir2022.wid.world/chapter-7/)は、2021年のさまざまな富裕層の個人の人数と、3つの世界的 な富裕税のシナリオに従って支払うべき純資産の合計と税金を示し ている。

        -   世界の億万長者は合計で13兆ドル以上を所有（世界の富の3.5％） • 資産100万ドル以上 6200万人（世界の成人人口の1.2％）。 • 資産1,000万ドル以上 180万人弱（上位0.04％） • 資産1億ドル以上 76,500人（上位0.001％） • 資産10億ドル以上 2,750人（上位0.00005％）

        -   国内総生産（GDP）：世界96.51兆ドル

        -   米国：23.32兆ドル；

        -   中国17.73兆ドル；日本4.941兆ドル（2021）

-   Chapter 8 Taxing Multinationals or Taxing Wealthy Individuals? [[Link](https://wir2022.wid.world/chapter-8/)]

    -   Total taxes paid by Income [[Link](https://wir2022.wid.world/chapter-8/)]

-   Chapter 9 Global vs Unilateral Perspectives on Tax Justice [[Link](https://wir2022.wid.world/chapter-9/)]

    -   タックスヘイブンは法人税や所得税の税率をゼロか、極めて低くしている国や地域を指します。

        -   パナマ文書: Panama Papers

    -   2021 年 10 月 8 日、経済協力開発機構（OECD）で検討が進められ てきた、いわゆるデジタル課税とミニマムタックスの主要な項目につ いて最終合意に至った。2023 年からの導入を目指すこととされた。

    -   ミニマムタックスは、実際に負担している税率（実効税率）が「 最低税率15％」を下回る場合に、本国の親会社等に上乗せ課税を 行うものである。⇒タックスヘブンへの税回避の動きを止めることが 期待されている。

-   Chapter 10 Emancipation, redistribution and sustainability [[Link](https://wir2022.wid.world/chapter-10/)]

    -   The rise of the Welfare State in rich countries (1910-1980) [[Link](https://wir2022.wid.world/chapter-10/)]

    -   Lessons from failed trickle-down economics [[Link](https://wir2022.wid.world/chapter-10/)], 10.4 [[Link](https://wir2022.wid.world/chapter-10/)]

        -   1980年代に大幅に減税した後、一人当たり所得の成長率は低下し ている。トリクルダウン経済学（減税による経済成長の促進）の主張 は正しくないことが実証されつつある。

        -   不平等が中間層の所得を減らし、経済停滞を招く原因になる。

    -   南北問題の間の資本と所得の流れの大きな不均衡に終止符を打つた めには、グローバリゼーションの基本原則を再評価する必要がある。

-   Glossary Country appendix [[Link](https://wir2022.wid.world/country-appendix-glossary/)]

01/09(TU)　Rでデータサイエンス3：GNI係数と所得分布　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-3.nb.html)]・ [[スライド](https://ds-sl.github.io/intro2r/ges001/ges00102.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00102.nb.html)]・[[ビデオ](https://youtu.be/RwD-SJlSHkQ)]

-   PositCloud 共有リンク：<https://posit.cloud/content/5539763>

    -   ジニって何！？（what_is_gini.Rmd） [[リンク](https://ds-sl.github.io/intro2r/ges001/what_is_gini.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/what_is_gini.Rmd)]

    -   ジニ指数と所得分布（gini.Rmd） [[リンク](https://ds-sl.github.io/intro2r/ges001/gini.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/gini.Rmd)]

        -   参考1/参考2付（gini_long.Rmd） [[リンク](https://ds-sl.github.io/intro2r/ges001/gini_long.nb.html)]

**Poverty and Inequality―Distribution of income or consumption（データが少ない難点）**

GINI index (World Bank estimate)；SI.POV.GINI [[Link](https://data.worldbank.org/indicator/SI.POV.GINI)]

Income share held by lowest 10%：SI.DST.FRST.10 [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SI.DST.FRST.10)]

Income share held by lowest 20%：SI.DST.FRST.20 [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SI.DST.FRST.20)]

Income share held by second 20%：SI.DST.02ND.20 [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SI.DST.02ND.20)]

Income share held by third 20%：SI.DST.03RD.20 [[Link](https://data.worldbank.org/indicator/SI.DST.03RD.20)]

Income share held by fourth 20%：SI.DST.04TH.20 [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SI.DST.04TH.20)]

Income share held by highest 20%：SI.DST.05TH.20 [[Link](https://data.worldbank.org/indicator/SI.DST.05TH.20)]

Income share held by highest 10%：SI.DST.10TH.10 [[Link](https://data.worldbank.org/indicator/SI.DST.10TH.10)]

### 第4週

01/11(TH)　南部アフリカ諸国の貧困と不平等の現状1

　　　　　　南部アフリカ諸国の貧困と不平等の現状2

第4週、第5週の講義では、貧困の問題が特に深刻な南部アフリカ諸国の問題を議論します。

World BankのINEQUALITY IN SOUTHERN AFRICA:AN ASSESSMENT OF THE SOUTHERN AFRICAN CUSTOMS UNION (<https://wir2022.wid.world/>)をテキストにしています。教育、失業、COVID-19の貧困に与える影響などを取り上げます。

#### コメント・レビュー

-   Trickle-down economics (トリクルダウン理論) [[リンク](https://en.wikipedia.org/wiki/Trickle-down_economics)]

-   中国の男女格差と今後の課題

-   人口問題の将来への影響

-   対外純資産：Net foreign assets (current LCU) FM.AST.NFRG.CN

    -   Net foreign assets are the sum of foreign assets held by monetary authorities and deposit money banks, less their foreign liabilities. Data are in current local currency.

-   External debt stocks (% of GNI) DT.DOD.DECT.GN.ZS

#### 南部アフリカ諸国の状況

-   INEQUALITY IN SOUTHERN AFRICA:AN ASSESSMENT OF THE SOUTHERN AFRICANCUSTOMS UNION [[Report](https://documents1.worldbank.org/curated/en/099125303072236903/pdf/P1649270c02a1f06b0a3ae02e57eadd7a82.pdf)] [[Link](https://openknowledge.worldbank.org/entities/publication/9f8e4073-25f9-562c-8e3b-541c99dd42cb)]

    -   Executive summary

    -   Chapter 1　Inequality in the Southern African Customs Union

    -   Chapter 2　The role of inherited circumstances

    -   Chapter 3　The role of the primary income distribution

    -   Chapter 4　The role of the secondary income distribution

    -   Chapter 5　The role of the tertiary income distribution and fiscal policy

    -   Chapter 6　The role of shocks

    -   Chapter 7　Addressing inequality in SACU: A policy discussion

    -   南アフリカ、レソト、エスワティニ、ナミビア、ボツワナ

01/16(TU)　Rでデータサイエンス4:貧困（データが少ない難点） [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-4.nb.html)]・[[スライド](https://ds-sl.github.io/intro2r/ges001/ges00110.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00110.nb.html)]・[[ビデオ](https://youtu.be/RwD-SJlSHkQ)]

**Poverty rates at national poverty lines**

Poverty headcount ratio at national poverty lines (% of population)：SI.POV.NAHC [[Link](https://data.worldbank.org/indicator/SI.POV.NAHC)]

National poverty headcount ratio is the percentage of the population living below the national poverty line(s). National estimates are based on population-weighted subgroup estimates from household surveys. For economies for which the data are from EU-SILC, the reported year is the income reference year, which is the year before the survey year.

全国貧困人口比率は、全国貧困線以下で生活している人口の割合です。国の推定値は、世帯調査からの人口加重サブグループ推定値に基づいています。データが EU-SILC からのものである経済の場合、報告される年は所得基準年、つまり調査年の前年です。

**Poverty and Inequality―Poverty rates at international poverty lines**

Poverty headcount ratio at \$2.15 a day (2017 PPP) (% of population)：SI.POV.DDAY [[Link](https://data.worldbank.org/indicator/SI.POV.DDAY)]

Poverty headcount ratio at \$2.15 a day is the percentage of the population living on less than \$2.15 a day at 2017 purchasing power adjusted prices. As a result of revisions in PPP exchange rates, poverty rates for individual countries cannot be compared with poverty rates reported in earlier editions.

1日2.15ドルの貧困人口比率は、2017年の購買力調整後価格で1日2.15ドル未満で生活している人口の割合です。PPP 為替レートの改定により、各国の貧困率を以前の版で報告された貧困率と比較することができなくなりました。

Poverty headcount ratio at \$3.65 a day (2017 PPP) (% of population)：SI.POV.LMIC [[Link](https://data.worldbank.org/indicator/SI.POV.LMIC)]

Poverty headcount ratio at \$3.65 a day is the percentage of the population living on less than \$3.65 a day at 2017 international prices.

1 日 3.65 ドルの貧困人口比率は、2017 年の国際価格で 1 日 3.65 ドル未満で生活している人口の割合です。

Poverty headcount ratio at \$6.85 a day (2017 PPP) (% of population)：SI.POV.UMIC [[Link](https://data.worldbank.org/indicator/SI.POV.UMIC)]

Poverty headcount ratio at \$6.85 a day is the percentage of the population living on less than \$6.85 a day at 2017 international prices.

1日6.85ドルの貧困人口比率は、2017年の国際価格で1日6.85ドル未満で生活している人口の割合です。

世銀の貧困データの計算についてやや詳しい解説

<https://www.worldbank.org/ja/news/feature/2014/01/08/open-data-poverty>

### 第5週

01/18(TH)　南部アフリカ諸国の貧困と不平等に対する対策

　　　　　　COVID-19が貧困に与えた影響

01/23(TU)　Rでデータサイエンス5　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-5.nb.html)]・ [[スライド](https://ds-sl.github.io/intro2r/ges001/ges00111.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00111.nb.html)]・[[ビデオ](https://youtu.be/WHIz4Vec4ek)]

**People-Education**

Government expenditure on education, total (% of GDP)：SE.XPD.TOTL.GD.ZS [[Link](https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS)]

General government expenditure on education (current, capital, and transfers) is expressed as a percentage of GDP. It includes expenditure funded by transfers from international sources to government. General government usually refers to local, regional and central governments.

教育に対する政府の一般支出（経常、資本、移転）は GDP の割合で表されます。これには、国際資金源から政府への送金によって資金提供された支出が含まれます。一般政府とは通常、地方自治体、地域政府、中央政府を指します。

School enrollment, primary (% gross)：SE.PRM.ENRR [[Link](https://data.worldbank.org/indicator/SE.PRM.ENRR)]

Gross enrollment ratio is the ratio of total enrollment, regardless of age, to the population of the age group that officially corresponds to the level of education shown. Primary education provides children with basic reading, writing, and mathematics skills along with an elementary understanding of such subjects as history, geography, natural science, social science, art, and music.

総就学率は、年齢に関係なく、表示されている教育レベルに正式に対応する年齢層の人口に対する総就学者数の比率です。初等教育では、子供たちに基本的な読み書き、数学のスキルと、歴史、地理、自然科学、社会科学、芸術、音楽などの科目の初歩的な理解を提供します。

School enrollment, secondary (% gross)：SE.SEC.ENRR [[Link](https://data.worldbank.org/indicator/SE.SEC.ENRR)]

Gross enrollment ratio is the ratio of total enrollment, regardless of age, to the population of the age group that officially corresponds to the level of education shown. Secondary education completes the provision of basic education that began at the primary level, and aims at laying the foundations for lifelong learning and human development, by offering more subject- or skill-oriented instruction using more specialized teachers.

総就学率は、年齢に関係なく、表示されている教育レベルに正式に対応する年齢層の人口に対する総就学者数の比率です。中等教育は、初等段階から始まった基礎教育の提供を完了し、より専門性の高い教師によるより教科や技能に特化した指導を行うことにより、生涯学習と人間形成の基礎を築くことを目的としています。

School enrollment, tertiary (% gross)：SE.TER.ENRR [[Link](https://data.worldbank.org/indicator/SE.TER.ENRR)]

Gross enrollment ratio is the ratio of total enrollment, regardless of age, to the population of the age group that officially corresponds to the level of education shown. Tertiary education, whether or not to an advanced research qualification, normally requires, as a minimum condition of admission, the successful completion of education at the secondary level.

総就学率は、年齢に関係なく、表示されている教育レベルに正式に対応する年齢層の人口に対する総就学者数の比率です。高等教育では、高度な研究資格の有無にかかわらず、通常、入学の最低条件として中等教育レベルの教育を無事に修了することが求められます。

**Health**

Mortality rate, under-5 (per 1,000 live births)：SH.DYN.MORT [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SH.DYN.MORT)]

Under-five mortality rate is the probability per 1,000 that a newborn baby will die before reaching age five, if subject to age-specific mortality rates of the specified year.

5 歳未満死亡率は、指定された年の年齢別死亡率が適用される場合に、新生児が 5 歳に達する前に死亡する 1,000 人あたりの確率です。

Incidence of HIV (% of uninfected population ages 15-49)：SH.HIV.INCD.ZS [[Link](https://data.worldbank.org/indicator/SH.HIV.INCD.ZS?locations=SZ)]

Number of new HIV infections among uninfected populations ages 15-49 expressed per 1,000 uninfected population in the year before the period.

期間の前の年間の非感染人口 1,000 人当たりの 15 ～ 49 歳の非感染集団における新規 HIV 感染者数。

**Gender**

School enrollment, primary and secondary (gross), gender parity index (GPI)：SE.ENR.PRSC.FM.ZS [[Link](https://data.worldbank.org/indicator/SE.ENR.PRSC.FM.ZS)]

Gender parity index for gross enrollment ratio in primary and secondary education is the ratio of girls to boys enrolled at primary and secondary levels in public and private schools.

初等中等教育における総就学率の男女平等指数は、公立および私立学校の初等および中等教育レベルに在籍する女子と男子の比率です。

Ratio of female to male labor force participation rate (%) (modeled ILO estimate)：SL.TLF.CACT.FM.ZS [[Link](https://data.worldbank.org/indicator/SL.TLF.CACT.FM.ZS)]

Labor force participation rate is the proportion of the population ages 15 and older that is economically active: all people who supply labor for the production of goods and services during a specified period. Ratio of female to male labor force participation rate is calculated by dividing female labor force participation rate by male labor force participation rate and multiplying by 100.

労働参加率とは、経済的に活動している 15 歳以上の人口の割合であり、指定された期間に商品やサービスの生産に労働力を供給するすべての人々を指します。女性労働力率と男性労働力率の比率は、女性労働力率を男性労働力率で割って100を乗じて算出します。

**Labor**

Unemployment, female (% of female labor force) (modeled ILO estimate)：SL.UEM.TOTL.FE.ZS [[Link](https://data.worldbank.org/indicator/SL.UEM.TOTL.FE.ZS)]

Unemployment refers to the share of the labor force that is without work but available for and seeking employment.

失業率とは、仕事はなくても職に就くことができ、求職している労働力の割合を指します。

Unemployment, male (% of male labor force) (modeled ILO estimate)：SL.UEM.TOTL.MA.ZS [[Link](https://data.worldbank.org/indicator/SL.UEM.TOTL.MA.ZS)]

Unemployment refers to the share of the labor force that is without work but available for and seeking employment.

失業率とは、仕事はなくても職に就くことができ、求職している労働力の割合を指します。

Global Link - Aid dependency

Net official development assistance and official aid received (current US\$) DT.ODA.ALLD.CD [[Link](https://data.worldbank.org/indicator/DT.ODA.ALLD.CD)]

Net official development assistance (ODA) consists of disbursements of loans made on concessional terms (net of repayments of principal) and grants by official agencies of the members of the Development Assistance Committee (DAC), by multilateral institutions, and by non-DAC countries to promote economic development and welfare in countries and territories in the DAC list of ODA recipients. It includes loans with a grant element of at least 25 percent (calculated at a rate of discount of 10 percent). Net official aid refers to aid flows (net of repayments) from official donors to countries and territories in part II of the DAC list of recipients: more advanced countries of Central and Eastern Europe, the countries of the former Soviet Union, and certain advanced developing countries and territories. Official aid is provided under terms and conditions similar to those for ODA. Part II of the DAC List was abolished in 2005. The collection of data on official aid and other resource flows to Part II countries ended with 2004 data. Data are in current U.S. dollars.

政府開発援助（ODA）の純額は、開発援助委員会（DAC）メンバーの公的機関、多国間機関、DAC非加盟国による、譲許的条件（元本返済を除く）で行われた融資の実行と助成金で構成されます。 DAC の ODA 受領者リストに含まれる国および地域の経済発展と福祉を促進する。これには、少なくとも 25 パーセント（割引率 10 パーセントで計算）の補助金要素を持つローンが含まれます。純公的援助とは、公的ドナーからDACの受取人リストのパートIIにある国および地域への援助の流れ（返済額を差し引いた額）を指します：中央および東ヨーロッパのより先進国、旧ソ連諸国、および一部の先進途上国国と地域。公的援助は、ODA と同様の条件で提供されます。DAC リストのパート II は 2005 年に廃止されました。パート II 諸国への公的援助およびその他の資源の流れに関するデータの収集は 2004 年のデータで終了しました。データは現在の米ドルで表示されます。

#### 演習の内容と課題

基本的には、PositCloud（<https://posit.cloud/）を使って実習>

探索的データ分析（EDA） -

練習と一つ目の課題（w5eda.Rmd） [[リンク](https://ds-sl.github.io/intro2r/ges001/w5eda.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/w5eda.Rmd)]

二つ目以降の課題：w5eda1.Rmd [[リンク](https://ds-sl.github.io/intro2r/ges001/w5eda1.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/w5eda1.Rmd)]

解答例：w5eda0.Rmd [[リンク](https://ds-sl.github.io/intro2r/ges001/w5eda0.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/w5eda0.Rmd)]

課題：2023.1.25. 23:59 までに Moodle の演習の課題ボックスに提出したものについては、なるべく、早く見て、フィードバックを書きます。それ以降に提出されたものも見ますが、フィードバックは遅くなると思ってください。

### 第6週

01/25(TH)　気候変動問題の原因：気候変動と経済活動1

　　　　　　気候変動問題の原因：気候変動と経済活2

第6週、第7週の講義では、気候変動が我々の生活にもたらす影響と対策を議論します。

基本的にIPCCの第6次評価報告書（<https://www.data.jma.go.jp/cpdinfo/ipcc/index.html> ）

をテキストに使っています。

01/30(TU)　Rでデータサイエンス6：気候変動　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-6.nb.html)]・[[スライド](https://ds-sl.github.io/intro2r/ges001/ges00112.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00112.nb.html)]・[[ビデオ](https://youtu.be/Zj_gK6XYaHs)]

Environment-Climate　

CO2 emissions (metric tons per capita) ：EN.ATM.CO2E.PC [[Link](https://data.worldbank.org/indicator/EN.ATM.CO2E.PC)]

Forest area (% of land area)：AG.LND.FRST.ZS [[Link](https://data.worldbank.org/indicator/AG.LND.FRST.ZS)]

Renewable electricity output (% of total electricity output)：EG.ELC.RNEW.ZS [[Link](https://data.worldbank.org/indicator/EG.ELC.RNEW.ZS)]

Electricity production from oil, gas and coal sources (% of total)：EG.ELC.FOSL.ZS [[Link](https://data.worldbank.org/indicator/EG.ELC.FOSL.ZS)]

Electricity production from nuclear sources (% of total)：EG.ELC.NUCL.ZS [[Link](https://data.worldbank.org/indicator/EG.ELC.NUCL.ZS)]

IEA:　Energy Statistics Data Browser　データ元

<https://www.iea.org/data-and-statistics/data-tools/energy-statistics-data-browser?country=WORLD&fuel=Energy%20supply&indicator=ElecGenByFuel>

#### 演習の内容

課題の解答例 [リンク](%5Bhttps://ds-sl.github.io/intro2r/ges001/w5eda0.nb.html)](<https://ds-sl.github.io/intro2r/ges001/w5eda0.nb.html>))

基本的には、PositCloud（<https://posit.cloud/>）を使って実習

-   探索的データ分析（EDA） -
    -   練習と一つ目の課題（w6eda.Rmd） [[リンク](https://ds-sl.github.io/intro2r/ges001/w6eda.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/w6eda.Rmd)]
    -   二つ目以降の課題：w6eda1.Rmd [[リンク](https://ds-sl.github.io/intro2r/ges001/w6eda1.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/ges001/w6eda1.Rmd)]

### 第7週

02/01(TH) 　気候変動に対する対策

　　　　　　 気候変動と貧困の連鎖

第7週は、南部アフリカや南アジアなど気候変動から大きな影響を受けている国々の現状を取り上げます。

#### コメント・レビュー

-   将来のことに関するいま生きている人の責任。将来の富を食い尽くす経済。

-   生活保護をうけていてアルバイトをしたときにその分が差し引かれてしまう。20万円ぐらい（年収249万位）それでは、働きたくないひとも生じてしまう。

-   アフリカのような貧しい国が多くの影響を受けてしまっている。緊急支援・開発援助・政策提案

-   2030年までに、CO2 排出を、43% 削減（現在40G ton 排出）：日本人、経済大国に住むものの責任

#### 講義

-   世界の１年間のCO2排出量は、40Gt CO2 - 日本は、1G ton（10億4400万トン）

    -   Carbon budget 2023 年現在 274Gt 1.5度以内に抑えるための累積排出量上限

-   Major flows from production to consumption

    -   温室効果ガスインベントリオフィス：<https://www.nies.go.jp/gio/>

-   Carbon Pricing: 迷惑財 - 負の公共財

    -   1t あたり CO2 に関する価格

        -   温対税　ガソリン 0.7円/L 289円

        -   化石燃料税：6310円

        -   パリ協定と整合性のあるレベル：15000円

        -   炭素除去技術（DAC）：約33000円

    -   カーボンリーケージ：国境炭素調節

-   SCOPE 計算方法

-   Climate group R100％ [[リンク](https://www.there100.org/re100-members?items_per_page=100)] - Apple など

    -   日本：村田製作所、Panasonic、FujisawaSST、ヤマトホールディングス

    -   環境省：地球環境・国際環境協力 [[リンク](https://www.env.go.jp/earth/)]

        -   “Supply-chain emissions” in Japan [[リンク](https://www.env.go.jp/earth/ondanka/supply_chain/gvc/en/files/supply_chain_en.pdf)]

-   発電

    -   洋上風力発電：ニュース：三菱商事が圧勝、Amazon、GE が後押し 11.99円/1Wh

-   政府の気候変動対策（欧州と日本）

    -   2021年6月28日、EU理事会は「欧州気候法 Fit for 55」を採択した。

    -   EUの排出量取引制度（EU ETS）の強化と範囲の拡大

    -   2023年05月12日: EU理事会（閣僚理事会）は4月25日、2030年の温室効果ガス（GHG） 削減目標（1990年比で少なくとも55％削減）を達成するための政策 パッケージ「Fit for 55」（注1）に関する5つの法案を採択

    -   1分からわかる、グリーン・ニューディール [[リンク](https://www.egmkt.co.jp/column/corporation/20220727_50.html)]

    -   日本が抱えるエネルギー問題 [[前編](https://www.enecho.meti.go.jp/about/special/johoteikyo/energyissue2022_1.html)]・[[後編](https://www.enecho.meti.go.jp/about/special/johoteikyo/energyissue2022_2.html)]

    -   GX関連法に残る問題点と必要な改善策 [[リンク](https://www.wwf.or.jp/activities/activity/5318.html)]

    -   太陽光発電：世界 2021年 5.3円、日本 13.8円 kWh [[資源エネルギー庁](https://www.enecho.meti.go.jp/about/special/tokushu/saiene/saienecost.html)][[REPOS](https://www.renewable-energy-potential.env.go.jp/RenewableEnergy/report/r01.html)][[リンク](https://earthene.com/media/180)]

    -   風力発電：頭の論理が追いつかない。すべてが驚きだ。[[リンク](https://www.nikkei.com/article/DGXZQOUC1057A0Q1A810C2000000/)]

    -   資源エネルギー庁：もっと知りたい！エネルギー基本計画③　再生可能エネルギー（3）高い経済性が期待される風力発電 [[リンク](https://www.enecho.meti.go.jp/about/special/johoteikyo/energykihonkeikaku2021_kaisetu03.html)]

#### Climate Ambition Summit [[Link](https://www.un.org/climatechange/climate-ambition-summit)]

02/06 (TU)　Rでデータサイエンス7：都市部と農村部の生活状況の格差　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-7.nb.html)]・[[スライド](https://ds-sl.github.io/intro2r/ges001/ges00120.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00120.nb.html)]・[[ビデオ](https://youtu.be/e0hdeQhi4xw)]

Urban and rural development

Access to electricity, urban (% of urban population)：EG.ELC.ACCS.UR.ZS [[Link](https://data.worldbank.org/indicator/EG.ELC.ACCS.UR.ZS)]

Access to electricity, rural (% of rural population)：EG.ELC.ACCS.RU.ZS [[Link](https://data.worldbank.org/indicator/EG.ELC.ACCS.RU.ZS)]

People using at least basic drinking water services, urban (% of urban population)：SH.H2O.BASW.UR.ZS [[Link](https://data.worldbank.org/indicator/SH.H2O.BASW.ZS)]

People using at least basic sanitation services, rural (% of rural population)：SH.STA.BASS.RU.ZS [[Link](https://data.worldbank.org/indicator/SH.STA.BASS.RU.ZS)]

People using at least basic sanitation services, urban (% of urban population)：SH.STA.BASS.UR.ZS [[Link](https://data.worldbank.org/indicator/SH.STA.BASS.UR.ZS)]

People using at least basic drinking water services, rural (% of rural population)：SH.H2O.BASW.RU.ZS [[Link](https://data.worldbank.org/indicator/SH.H2O.BASW.RU.ZS)]

### 第8週

02/08(TH)　紛争と貧困の連鎖1

            紛争と貧困の連鎖2

第8週と第9週では、戦争、気候変動、COVID-19の複合的要因が世界的な食糧危機を引き起こし、格差と貧困を加速させている現状について、議論します。

Fragility and Conflict: On the Front Lines of the Fight against Poverty [[Link](https://www.worldbank.org/en/topic/poverty/publication/fragility-conflict-on-the-front-lines-fight-against-poverty)]

#### 講義

-   コメント

    -   地熱発電もある。

    -   炭素税：カーボンプライシング 2033? （GX 関連法案）2026? （下の p5）

        -   グリーントランスフォーメーションの推進に向けて -成長志向型カーボンプライシングを中心に（2024/05/29）経済産業省 環境経済室 [[リンク](https://www.meti.go.jp/shingikai/sankoshin/sangyo_gijutsu/chikyu_kankyo/ondanka_follow_up/pdf/2023_001_05_00.pdf)]

    -   国境炭素調整 vs カーボンリケージので会メリットをカバー [[リンク](https://www.meti.go.jp/shingikai/energy_environment/carbon_neutral_jitsugen/pdf/001_02_00.pdf)]

    -   二酸化炭素を除去しても、破壊された自然をもとには戻せない（地球温暖化の不可逆性）

    -   原子力発電所 vs 認知バイアス - 正常化バイアス

-   紛争と貧困

    -   地球公共財（非排除性・非競合性[^1]）としての「平和」日本平和学会

        -   UNDP: Public Common Goods (1999)

        -   地球をひとつの共同体として捉え、そこでの公共利益 を考察することが地球公共財の議論の主題

        -   武器は私的財

    -   Global Peace Index 2023 （IEP）[[リンク](https://www.visionofhumanity.org/wp-content/uploads/2023/06/GPI-2023-Web.pdf)]

        -   <https://www.economicsandpeace.org/>

        -   紛争による死亡 23万人（2022）96% 増加

        -   暴力の背系経済への GDP への影響 13%

        -   暴力の連鎖を打破するためには，市民に安全と正義，及び雇用を提供するための正当な制度と統治を強化することが決定的に重要で

            -   市民の安全と，正義，及び雇用に対する投資が暴力の削減にとっては必要不可欠である．

    -   Positive Peace

        -   近隣諸国との友好関係　と　情報の自由な流れ

    -   世界開発報告 (WDR) [[日本語リンク](https://www.worldbank.org/ja/country/japan/publication/world-development-report)]

        -   [世界開発報告2011 [リンク][日本語リンク]](https://openknowledge.worldbank.org/bitstream/handle/10986/4389/589880JAPANESE067926B09784903532776.pdf?sequence=16)

        -   制度の変化が必要：人道的支援機関と開発機関の間の調整を改善する必要がある．

            -   脆弱で紛争経験という環境に関与したドナーにとっ ては二重の説明責任というジレンマがある

    -   Fragility and Conflict: On the Front Lines of the Fight against Poverty [[リンク](https://www.worldbank.org/en/topic/poverty/publication/fragility-conflict-on-the-front-lines-fight-against-poverty)] - World Bank, FEBRUARY 27, 2020

        -   FCS: fragile and conflict-affected situations [[リンク](https://openknowledge.worldbank.org/entities/publication/3c335532-5484-51a4-a16f-78399ab2f025)], [[レポートリンク](https://openknowledge.worldbank.org/server/api/core/bitstreams/ebc3ef9e-ca7f-5959-8dfe-2a8a1f2a25dc/content)]

        -   紛争によって大きく分断された2つのスピードの世界が出現している。 一方では、FCSのない経済が極度の貧困を大幅に削減し、さらなる開 発の進展に道を開いている。

        -   今後数十年の間に、紛争や制度の脆弱性に悩まされていない経済が 開発の階段を上り続ける可能性が高い中、世界の貧困はますます FCSに属する経済に集中することになるでしょう。

        -   Overlapping deprivations are more pronounced economies in FCS: 19.8% vs 6.6%

        -   Growth is negatively correlated with conflict deaths and fragility

        -   Most people living in FCS also doubt that things with get better

        -   まとめ：

            -   FCS地域では、深刻な暴力や心的外傷後の経験、基本的なインフラ （例えば、水や電気）の欠如、質の高いヘルスケアや教育へのアクセ スの欠如などが同時に起きている。

            -   これらの要因は、貧しい人々の人的資本の形成を阻害し、経済成長 を阻害している。

        -   紛争が貧困と福祉に及ぼす長期的な影響　[[Link](https://www.worldbank.org/en/publication/worldwide-governance-indicators)]

        -   紛争は、人的資本や生産性を損なうことで経済の発展を阻害し、 その影響は何世代にもわたって続く。

        -   脆弱性のプロファイルごとに国を分類すると、2 つの重要な発見 がある。第一に、FCS諸国内には大きな不均質性があり、より効果的 な解決策を講じるためには、差別化された政策が必要である。第二 に、脆弱性は、FCS諸国と非FCS諸国の両方に存在し、予防措置の ために監視される必要がある

        -   世界の貧困層の大半が住むであろうFCS経済圏での劇的かつ持続 的な貧困削減なくして、世界の貧困目標は達成されない。

        -   貧困と紛争の連鎖を断ち切るための包括的な努力の成否は、FCS の貧困層にとって重要である。多くの人々にとって、これらの政策が いかにうまく機能するかが、彼らの生存の可能性を左右するのであ る。世界で最も弱い立場にある何百万人もの人々の希望と、しばし ば命がかかっていることは、行動するのに十分な理由である。しかし 、FCSにおける貧困削減と機会拡大の恩恵は、直接関係する人々や FCSの境界を越えて、はるかに広がるだろう。

[^1]: 教育はどうだろうか。高等教育は、非競合的とは言えず、非排他的とも言えない。

02/13(TU)　Rでデータサイエンス8：難民、軍事支出　 [[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-8.nb.html)]・[[スライド](https://ds-sl.github.io/intro2r/ges001/ges00121.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00121.nb.html)]・[[ビデオ](https://youtu.be/mq2Y83CGI4Q)]

**Global Link-Refugees**

Refugee population by country or territory of asylum：SM.POP.REFG [[Link](https://data.worldbank.org/indicator/SM.POP.REFG)]

Refugee population by country or territory of origin：SM.POP.REFG.OR [[Link](https://data.worldbank.org/indicator/SM.POP.REFG.OR)]

Net ODA received (% of GNI)：DT.ODA.ODAT.GN.ZS [[Link](https://data.worldbank.org/indicator/DT.ODA.ODAT.GN.ZS)]

Net official development assistance and official aid received (current US\$)：DT.ODA.ALLD.CD [[Link](https://data.worldbank.org/indicator/DT.ODA.ALLD.CD)]

Net ODA received (% of central government expense)：DT.ODA.ODAT.XP.ZS [[Link](https://data.worldbank.org/indicator/DT.ODA.ODAT.XP.ZS)]

Military expenditure (current USD)：MS.MIL.XPND.CD [[Link](https://data.worldbank.org/indicator/MS.MIL.XPND.CD)]

Military expenditure (% of general government expenditure)：MS.MIL.XPND.ZS [[Link](https://data.worldbank.org/indicator/MS.MIL.XPND.ZS)]

Arms imports (SIPRI trend indicator values)：MS.MIL.MPRT.KD [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/MS.MIL.MPRT.KD)]

Arms exports (SIPRI trend indicator values)：MS.MIL.XPRT.KD [[Link](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/MS.MIL.XPRT.KD)]

### 第9週

02/15(TH)  紛争と貧困の連鎖3

　　　　　  紛争と貧困の連鎖を断ち切る方法

FAO: The Importance of Ukraine and the Russian Federation for Global Agricultural Markets and the Risks Associated with the War in Ukraine [[Link](https://www.fao.org/3/cb9236en/cb9236en.pdf)]

戦争が引き起こす食料危機の現状と解決策を考える。

#### 講義

-   コメント

    -   Pro-active contribution to peace 積極平和主義

    -   分断・二極化、ロシアでは、犯罪なども減っている。

-   ウクライナ戦争と食糧危機

    -   ＡＯ＝国連食糧農業機関のチーフエコノミスト、マッシモ・トレロ氏トレロ氏は、「世界の食料価格は、開戦直後の歴史的な高騰こそ落ち着いてきたものの、依然として高い水準にある」としたうえで、「ことしは、
        アフリカ、中東、アジアなどの貧しい国々で、必要な量の食料を入手できなくなり、飢餓が広がるおそれがある」。「まずは、ウクライナの穀物輸出を継続させるため、ロシアとの合意を更新することが必要だ」。

    -   ロシアとウクライナは、ともに穀物の輸出大国です。小麦の輸出量は、戦争前、ロシアが世界第１位、ウクライナが第５位で、この両国で、世界のおよそ３０％を占め、とうもろこしも、両国で２０％を占めていました。両国からの輸出が大きく減り、世界の食料価格が高騰しました。

    -   Global Food Report 2023: International Food Policy Research Institute (IFPRI)　[[Link](https://www.ifpri.org/publication/global-food-policy-report-2023-rethinking-food-crisis-responses)]

    -   穀物メジャーの暗躍: 欧米によるロシアへの経済制裁が穀物の国際価格急騰を招き、世界中で食料危機が懸念されるなかで、膨大な利益を求めて暗躍しているのが穀物市場を支配する穀物メジャーの存在だ

    -   穀物メジャーは、小麦、大豆、トウモロコシなどの主要穀物を世界中で買い付け、集荷、輸送、保管までを
        手掛ける多国籍企業で、アメリカや欧州に本社を置く上位5社で世界の穀物取引の約8割を支配し、穀物流通に多大な影響力を持っている。

    -   経営規模は上位2社が群を抜き、首位の米カーギル社が自社で調達する穀物は年約7500万㌧、2位の米アー
        チャー・ダニエルズ・ミッドランド(ADM)は約6500万㌧と推定されている。カーギルは66カ国に15万人以上の従業員を持ち、世界の穀物シェアの四割を握るといわれている。ADMは世界の160カ国で事業を展開している。

-   **Eiman Yassin, Understanding the Middle East Society and the Palestinian Experience: History, Present and Future**

    -   Three important values: religion (in ID), family, work

    -   22 Arab countries, Arabic, Islam, Muslim people

    -   Flag of Palestine [[Link](https://www.britannica.com/topic/flag-of-Palestine-Liberation-Organization)]

    -   Monotheism: Judaism, Christianity, Islam

    -   Thobe, a long, loose-fitting dress. Kuffiyeh, traditional Palestinian scarf

    -   Theodor Herzl: [[Wikipedia](https://en.wikipedia.org/wiki/Theodor_Herzl)] シオニズム

        -   Zionism is a nationalist movement that emerged in the 19th century to enable the establishment of a homeland for the Jewish people in Palestine a region roughly corresponding to the Land of Israel in Jewish tradition. Following the establishment of the modern state of Israel, Zionism became an ideology that supports the development and protection of the State of Israel as a Jewish state.

        -   November 1917

    -   Balfour Declaration

        -   Dear Lord Rothschild, I have much pleasure in conveying to you, on behalf of His Majesty's Government, the following declaration of sympathy with Jewish Zionist aspirations which has been submitted to, and approved by, the Cabinet. His Majesty's government view with favor the establishment in Palestine of a national home for the Jewish people, and will use their best endeavors to facilitate the achievement of this object, it being clearly understood that nothing shall be done which may prejudice the civil and religious rights of existing non-Jewish communities in Palestine, or the rights and political status enjoyed by Jews in any other country.

    -   1973: Those three Arab countries started a war against Israel and won the war and was able to return back their lands

    -   Hamas attack on October 7, 2023

    -   Gaza death toll 28,064 Palestinians killed 67,611 injured

    -   South African representatives argued before the International Court of Justice that Israel is engaged in a genocidal assault on the Gaza Strip, subjecting the enclave to "merciless" bombing with the clear intent to wipe out the Palestinian population.

    -   Itochu Corp's aviation unit will end its strategic cooperation with Israeli defence company Elbit Systems Ltd (ESLT.TA), by the end of February amid the war in Gaza, the Japanese trading house's executive said on Monday. Itochu plans to end the collaboration after the World Court ordered Israel last month to prevent acts of genocide against Palestinians and do more to help civilians, Itochu Chief Financial Officer Tsuyoshi Hachimura said. (Feb. 5, 2024, Asahi-Shinbun Digital)

02/20(TU)　Rでデータサイエンス9：まとめと演習　[[準備](https://ds-sl.github.io/intro2r/ges001/ges001-prep-9.nb.html)]・[[スライド](https://ds-sl.github.io/intro2r/ges001/ges00122.html)]・[[R Notebook](https://ds-sl.github.io/intro2r/ges001/ges00122.nb.html)]・[ビデオ]

### 第10週

02/22(TH)　特別講義（千葉真先生）

資本主義と民主主義の関係について、政治学の立場から議論します。

「資本主義・デモクラシー・エコロジー」[[Link](https://www.chikumashobo.co.jp/product/9784480017437/)]

#### 特別講義：今日の環境危機とそれへの取り組みについて- 政治理論の視点から

1.  はじめに

    -   民主主義、国家主義、資本主義

2.  自由民主主義が試されている「試される民主主義」

    -   代表制民主主義 (representative democracy)、参加民主主義 (participatory democracy)

    -   日本では、一と二分の一体制

    -   福祉国家（welfare state）のもとで、40年間、自由民主主義体制が、徹底平和主義とも連動して維持されてきた。これが崩れつつある。（24条、生存権）

    -   ヤン・ウェルナー・ミラー「自由民主主義は多くの人々にとってデフォルトではなくなりつつある」80年代半ばから。

    -   福祉国家型資本主義からネオ・リベラリズム（新自由主義）型資本主義にとって替えられた。

        -   20 世紀末以降は、製造業中心から 株・投資（投機との違いが不分明化）・金融中心のグローバル資本主義、国民経済とし て発展してきた資本主義からグローバルな資本主義へと変容。

            -   要因：① 経済成長の陰り、② グローバル・ノースとグローバル・サウス の構造的格差の激化、③ 環境（エコロジー）危機の深刻化と地球温暖化、④ 気候変動 と「人新世時代」の到来、⑤「ネオ・リベラリズム」（新自由主義）と「新右派連合」の 形成など。

            -   デ ヴィッド・ハーヴェイ「新自由主義とは何よりも、強力な私的所有権、自由市場、自由 貿易を特徴とする制度的枠組みの範囲内で個々人の企業活動の自由とその能力とが無 制約的に発揮されることによって人類の富と福利が最も増大する、と主張する政治経済 的実践の理論である」

        -   1980 年代のポスト福祉国家を 標榜するレーガン＝サッチャー＝中曽根式の「新保守主義」

            -   規制緩和、市 場至上主義、自己利益のマキシマム化を指向→公共性の著しい欠如、社会保障と社会福 祉の劣化、社会的弱者（貧窮者・母子家庭・女性・若者・非正規雇用者）保護の減退

                -   トリクルダウン理論（トリクルダウンりろん、英: trickle-down effect）とは、「富める者が富めば、貧しい者にも自然に富がこぼれ落ち、経済全体が良くなる」とする経済理論である。

            -   ブランコ・ミラノヴィッチ『資本主義だけ残った』（みすず書房、2019 年）

3.  エコロジー危機と政治

    -   ① 環境汚染と資源の枯渇、② 人口・食糧・エネルギ ー問題、③ 熱帯林の破壊と巨大な山火事、④ 地球温暖化による気候変動。

    -   1988 Time: Man of the Year, 絶滅寸前の地球 Endangered Earth, Planet of the Year \| Jan. 2, 1989 [[リンク](https://content.time.com/time/covers/0,16641,19890102,00.html)]

        -   Planet Of The Year: What on EARTH Are We Doing?　[[リンク](https://content.time.com/time/subscriber/article/0,33009,956627-5,00.html)]

    -   パウル・クルッツェンによる 2010 年の「人新世時代」（アントロポセン/the Anthropocene）の始まり

    -   ① 持 続 可 能 な 発 展 （ sustainable development ）、 ② 定 常 型 経 済 （ stationary economics ）、 ③ 脱 成 長 （ degrowth, décroissance）

        -   ① は経済成長と温暖化による異常気象の克服を何とか両立させよ うとする試み。

        -   ②ハ 6 ーマン・デイリーや広井良典や古くはジョン・スチュアート・ミルなど。

4.  付論 日本の安全保障政策の新局面

    -   中村哲「アフガニスタンの実体験において、確信できることがある。武力によってこ の身が守られたことはなかった。防備は必ずしも武器によらない」（『天、共に在り』 2013 年、244 頁）

    -   2022 年 12 月 16 日に岸田政権が「安全保障三文書」（「国家安全保障戦略」、「国家防 7 衛戦略」 、「防衛力整備計画」 ）を閣議決定した。

        -   ① 戦後日本の政治と外交と安全保障の根幹を作り上げてきた日本国憲 法の非戦=平和主義の大原則からの明白な逸脱。

        -   ② これだけ重要な決定を、立法の最高 機関である国会に諮ることなく、それを通さずに行政部だけで決定。

        -   ③ 初めの二文書 では「中国、北朝鮮、ロシア」を仮想敵国として明示。

        -   ④ 防衛費の国家予算を GDP 比 1％枠を撤廃し、5 年間で倍増の 2%まで増強し、43 兆円とするという決定。

        -   ⑤「敵基地攻撃」能力の保持を謳い、先制攻撃のリスクを持ち、これまでの「専守防衛」の原則 からの逸脱の可能性が高い。

#### 質疑

-   アメリカべったりの日本が、中国の脅威とどう向き合うか

-   若い世代がどのように政治と向き合うか

02/27(TU)　まとめ

データサイエンスについて

海蔵寺先生：

-   COP28に際して若者の緊急声明ー1.5度目標やってるふりはもうやめてー：[[リンク](https://fridaysforfuture.jp/cop28に際して若者の緊急声明ー1-5度目標やってるふり/)]

-   「防衛装備移転三原則」改正　日本産の迎撃ミサイル「パトリオット」米に輸出決定(2023年12月22日) <https://www.youtube.com/watch?v=qRW_2CkBqLU>

**03月02日：レポート提出**

## 成績評価

経済学パートではレポートが60%程度、講義への参加（コメントシートを含む）が40%程度の合計で評価される。

データサイエンスの確認問題 20%

### 期末レポート

講義では、貧困と不平等の拡大の原因として、「富裕層への富の集中」、「機会の不平等」、「気候変動」、「紛争」、などを取り上げ、貧困や不平等の拡大を防ぐ対策について考えた。また、気候変動については今後の自然環境や人間生活に与える影響を分析し、気候変動対策について考えた。講義の内容を踏まえて、下記の課題から一つを選び、経済学的な視点からレポートを作成しなさい。

１．貧困と不平等拡大の原因を調べ、貧困がもたらす悪影響を解決する方法を経済的視点から論じなさい。

２．気候変動問題の現状と原因を調べ、気候変動がもたらす悪影響を解決する方法を経済的視点から論じなさい。

３．紛争の現状と原因を調べ、紛争がもたらす悪影響を解決する方法を経済的視点から論じなさい。

長さ：A45枚程度　PDFファイルで提出すること。（ファイル名にID、氏名を書いてください。）

締め切り：03月02日（23：59）；　提出場所：Moodle上の提出Box
