---
title: "R Notebook"
output: html_notebook
---

### GDP（Gross Domestic Product）

GDPには、名目(nominal)と実質(real)という二つの尺度があります。名目はその時の価格で評価したGDPの値です。(current US$).実質GDPは、基準年例えば2015年の価格で評価したGDPです。World Bank、OECDとも対USドルの為替レートを使う場合基準年を2015年価格に置いています。下の二つを名目GDP実質GDPとして使うのが良いと思います。　

### GDP (current US$) 
GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current U.S. dollars. Dollar figures for GDP are converted from domestic currencies using single year official exchange rates. For a few countries where the official exchange rate does not reflect the rate effectively applied to actual foreign exchange transactions, an alternative conversion factor is used. 

ID: NY.GDP.MKTP.CD 
Source: World Bank national accounts data, and OECD National Accounts data files. 
License:  CC BY-4.0 


### GDP (constant 2015 US$) 

GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant 2015 prices, expressed in U.S. dollars. Dollar figures for GDP are converted from domestic currencies using 2015 official exchange rates. For a few countries where the official exchange rate does not reflect the rate effectively applied to actual foreign exchange transactions, an alternative conversion factor is used. 

ID: NY.GDP.MKTP.KD 

Source: World Bank national accounts data, and OECD National Accounts data files. 
License:  CC BY-4.0 

実質GDP成長率は、以下です。2015年価格が基準年として使われています。　

### GDP growth (annual %) 

Annual percentage growth rate of GDP at market prices based on constant local currency.  Aggregates are based on constant 2015 prices, expressed in U.S. dollars. GDP is the sum of  gross value added by all resident producers in the economy plus any product taxes and minus  any subsidies not included in the value of the products. It is calculated without making  deductions for depreciation of fabricated assets or for depletion and degradation of natural  resources. 

ID: NY.GDP.MKTP.KD.ZG 

Source: World Bank national accounts data, and OECD National Accounts data files. 
License:  CC BY-4.0 


以下参考に、PPP（購買力平価）を使ったGDPの計算です。これは、為替レートを各国の物価水準で調整して、GDPを計算しています。　

GDP, PPP (current international $)

This indicator provides values for gross domestic product (GDP) expressed in current international dollars, converted by purchasing power parity (PPP) conversion factor. GDP is the sum of gross value added by all resident producers in the country plus any product taxes and minus any subsidies not included in the value of the products. PPP conversion factor is a spatial price deflator and currency converter that eliminates the effects of the differences in price levels between countries. From April 2020, “GDP: linked series (current LCU)” [NY.GDP.MKTP.CN.AD] is used as underlying GDP in local currency unit so that it’s in line with time series of PPP conversion factors for GDP, which are extrapolated with linked GDP deflators.

ID: NY.GDP.MKTP.PP.CD

Source: International Comparison Program, World Bank | World Development Indicators database, World Bank | Eurostat-OECD PPP Programme.
License:  CC BY-4.0


GDP, PPP (constant 2017 international $)

PPP GDP is gross domestic product converted to international dollars using purchasing power parity rates. An international dollar has the same purchasing power over GDP as the U.S. dollar has in the United States. GDP is the sum of gross value added by all resident producers in the country plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant 2017 international dollars.

ID: NY.GDP.MKTP.PP.KD

Source: International Comparison Program, World Bank | World Development Indicators database, World Bank | Eurostat-OECD PPP Programme.
License:  CC BY-4.0




## GDP per capita 

GDPを国の全人口で割った値です。ＧＤＰに合わせて、以下の2つを使うのが良いと思います。　

### GDP per capita (current US$)
GDP per capita is gross domestic product divided by midyear population. GDP is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current U.S. dollars.

ID: NY.GDP.PCAP.CD

Source: World Bank national accounts data, and OECD National Accounts data files.
License:  CC BY-4.0


### GDP per capita (constant 2015 US$)

GDP per capita is gross domestic product divided by midyear population. GDP is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant 2015 U.S. dollars.

ID: NY.GDP.PCAP.KD

Source: World Bank national accounts data, and OECD National Accounts data files.
License:  CC BY-4.0 
Aggregation Method: Weighted average
BasePeriod: 2015

以下は、名目GDP per capitaの成長率です。実質ＧＤＰpercapitaの成長率を計算する場合は、
GDP per capita (constant 2015 US$)を使う必要があります。　

### GDP per capita growth (annual %)

Annual percentage growth rate of GDP per capita based on constant local currency. GDP per capita is gross domestic product divided by midyear population. GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources.

ID: NY.GDP.PCAP.KD.ZG

Source: World Bank national accounts data, and OECD National Accounts data files.
License:  CC BY-4.0
https://data.worldbank.org/indicator/NY.GDP.PCAP.KD.ZG



以下、PPPを使って計算した一人当たりＧＤＰの例です。　

GDP per capita, PPP (current international $)  

This indicator provides per capita values for gross domestic product (GDP) expressed in current international dollars converted by purchasing power parity (PPP) conversion factor. GDP is the sum of gross value added by all resident producers in the country plus any product taxes and minus any subsidies not included in the value of the products. conversion factor is a spatial price deflator and currency converter that controls for price level differences between countries. Total population is a mid-year population based on the de facto definition of population, which counts all residents regardless of legal status or citizenship.

ID: NY.GDP.PCAP.PP.CD 

Source: International Comparison Program, World Bank | World Development Indicators database, World Bank | Eurostat-OECD PPP Programme. 
License:  CC BY-4.0 


GDP per capita, PPP (constant 2017 international $)  

GDP per capita based on purchasing power parity (PPP). PPP GDP is gross domestic product converted to international dollars using purchasing power parity rates. An international dollar has the same purchasing power over GDP as the U.S. dollar has in the United States. GDP at purchaser's prices is the sum of gross value added by all resident producers in the country plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant 2017 international dollars. 

ID: NY.GDP.PCAP.PP.KD  

Source: International Comparison Program, World Bank | World Development Indicators database, World Bank | Eurostat-OECD PPP Programme. 
License:  CC BY-4.0  
Aggregation Method: Weighted average 
BasePeriod: 2017 




### Inflation 

Inflation, GDP deflator (annual %) 

Inflation as measured by the annual growth rate of the GDP implicit deflator shows the rate of price change in the economy as a whole. The GDP implicit deflator is the ratio of GDP in current local currency to GDP in constant local currency.

ID: NY.GDP.DEFL.KD.ZG 

Source: World Bank national accounts data, and OECD National Accounts data files. 
License:  CC BY-4.0 

Aggregation Method: Median 
https://data.worldbank.org/indicator/NY.GDP.DEFL.KD.ZG 

GDP Deflatorを使う場合、GDPが、local currencyで計算されているため、GDP (current LCU)とGDP (constant LCU)を使う必要があります。 

GDP(current LCU) = GDP Deflator x GDP (constant LCU)  

の関係になっています。　

GDP （current LCU）　

GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current local currency. 

ID: NY.GDP.MKTP.CN 

Source: World Bank national accounts data, and OECD National Accounts data files. 
License:  CC BY-4.0  

GDP (constant LCU)　

GDP is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant local currency.　

ID: NY.GDP.MKTP.KN　

Source: World Bank national accounts data, and OECD National Accounts data files.　
License:  CC BY-4.0 
BasePeriod: varies by country　

Inflation, consumer prices (annual %) 

Inflation as measured by the consumer price index reflects the annual percentage change in the cost to the average consumer of acquiring a basket of goods and services that may be fixed or changed at specified intervals, such as yearly. The Laspeyres formula is generally used. 

ID: FP.CPI.TOTL.ZG 

Source: International Monetary Fund, International Financial Statistics and data files. 
License:  CC BY-4.0  

Aggregation Method: Median 
https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG 

