---
title: "Data Analysis for Researchers"
author: "Hiroshi Suzuki"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

## Week 1 (2023/12/13)

Only Part II. [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-01.html#1)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-01.nb.html)], [[Video](https://youtu.be/mpnoKZgpBYY)]

-   R and RStudio

-   PositCloud

-   Installation of R and RStudio

### Files

-   Purchasing power parities (PPPs) [[Link](https://ds-sl.github.io/intro2r/da4r/gdp_ppp.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/gdp_ppp.Rmd)]

## Week 2 (2023/12/20)

Exploratory Data Analysis I [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-02.html#1)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-02.nb.html)], [[Video1](https://www.youtube.com/watch?v=p34Jf5WTrF4)], [[Video2](https://www.youtube.com/watch?v=EGS6ZiFccf8)]

### Part I

-   R and RStudio: Installation +

    -   Get started with RStudio

    -   Creating a project, starting with a project

    -   `R.version.string`, Package updates

    -   Installation of Packages

-   Posit Cloud

    -   Update R version

    -   Package updates

-   A short introduction to R

    -   First three or four

        -   head(iris)

        -   str(iris)

        -   summary(iris)

        -   plot(iris\$Petal.Length, iris\$Petal.Width)

    -   Assignment and piping

        -   df_iris \<- iris

        -   df_iris[c(3,4)] \|\> plot()

        -   lm(iris\$Petal.Length \~ iris\$Petal.Width, df_iris)

        -   df_iris \|\> lm(iris\$Petal.Length \~ iris\$Petal.Width, data = \_)

    -   Subsetting

        -   df_iris[3,4]

        -   df_iris[c(3,4)]

        -   df_iris[c(3,4,5)]

        -   df_iris[3:5]

        -   df_iris[[5]] \|\> unique()

        -   df_iris\$Species \|\> unique()

    -   Classes and Types - *not included*

        -   class(df_iris)

        -   class(df_iris[5])

        -   class(df_iris[[5]])

        -   typeof(df_iris[[1]])

        -   typeof(df_iris[[5]])

-   Gapminder [[Link](https://www.gapminder.org)]

    -   Upgrade Your Worldview

    -   Dollar Street

    -   Animation Charts

        -   Babies per woman vs Life expectancy [[Link](https://www.gapminder.org/tools/#$model$markers$bubble$encoding$x$data$concept=children_per_woman_total_fertility&source=sg&space@=country&=time;;&scale$domain:null&zoomed:null&type:null;;;;;;&chart-type=bubbles&url=v1)]

            -   Total fertility vs Life expectancy at birth

            -   How many variables?

        -   About Data: Fact \> Data [[Link](https://www.gapminder.org/data/)]

-   World Development Indicators: Data themes [[Link](https://datatopics.worldbank.org/world-development-indicators/)]

    -   Find data you want to study. Record the name, WDI code, and possibly the URL.

    -   People [[Link](https://datatopics.worldbank.org/world-development-indicators/themes/people.html)]

        -   Population, total: SP.POP.TOTL [[Link](https://data.worldbank.org/indicator/SP.POP.TOTL)]

        -   Fertility rate, total (births per woman): SP.DYN.TFRT.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.TFRT.IN)]

        -   Life expectancy at birth, total: SP.DYN.LE00.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)]

### Part II

-   R Notebook: life-expectancy

-   `df_lifeexp <- WDI(indicator = c(pop = " SP.POP.TOTL", fertility = "SP.DYN.TFRT.IN", lifeexp = "SP.DYN.LE00.IN"))`

-   `dplyr`, a package in tidyverse

    -   `filter()`

    -   `distinct()`

    -   `drop_na()`

-   ggplot2

    -   `ggplot(aes(x=var1, y=var2))`

    -   Scatter Plot: ``` geom_point(aes(``col=var3, size=var4, shape=var5``)) ```

    -   Line Graph: ``` geom_line(``aes(col=var3, linetype=var4))``) ```

### Files

-   Life Expectancy [[Link](https://ds-sl.github.io/intro2r/da4r/life_expectancy.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/life_expectancy.Rmd)]

### Assignment 1

-   Self-introduction and 'Please call me ... .'

-   What do you expect from this course?

-   Write the name and the WDI code of the WDI data you are interested in. Reason?

-   List the data you want to study and investigate, if any.

### Recommended Readings and Activities

1.  World Development Indicators: Data themes [[Link](https://datatopics.worldbank.org/world-development-indicators/)]

    -   Find data you want to study. Record the name, WDI code, and possibly the URL.

2.  Posit Primers - interactive exercises: The Basics [[Link](https://posit.cloud/learn/primers/1)]

    1.  [Visualization Basics](https://posit.cloud/learn/primers/1.1)

    2.  [Programming Basics](https://posit.cloud/learn/primers/1.2)

RStudio IDE Cheat Sheet. PDF is available on the top right. [[Site Link](https://rstudio.github.io/cheatsheets/html/rstudio-ide.html)]

## Week 3 (2024/01/10)

Exploratory Data Analysis II [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-03.html#1)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-03.nb.html)], [[Video1](https://youtu.be/SfnYiNBpLVc)], [[Video2](https://youtu.be/sRSkp8HvP6M)]

-   Hypothesis testing!? Hypothesis creating.

WDI

-   The World Bank Data Catalog [[Link](https://datacatalog.worldbank.org/home)]

    -   World Development Indicators [[Link](https://datacatalog.worldbank.org/search/dataset/0037712/World-Development-Indicators)] \> [[Excel File](https://databank.worldbank.org/data/download/WDI_EXCEL.zip)]

### Part I

Exploration of data using one or two related WDI indicators with extra = TRUE

-   dplyr

    -   select

    -   group_by

    -   summarize

-   ggplot2

    -   line graph

    -   box plot

    -   scatter plot

    -   bar plot and column plot

    -   histogram with colors

    -   smooth plot

### Part II - Practicum

-   Going through EDA using WDI

    -   [[Link](https://ds-sl.github.io/intro2r/da4r/co2pcap.nb.html)]

-   Your chosen indicator(s)

-   WDI template [[Link](https://ds-sl.github.io/intro2r/intro2wdi/wdi_temp.nb.html)]

### Recommended Readings and Activities

1.  Posit Recipes（New edition of Posit Primers）: interactive exercises [[Link](https://posit.cloud/learn/recipes)]

### Assignment 2

## Week 4 (2024/01/17)

Exploratory Data Analysis III [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-04.html)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-04.nb.html)], [[Video1](https://youtu.be/8J6DBKSriGs)], [Video2]

### Part I

-   Data with related variables in WDI

-   tidyr

    -   pivot_longer

        -   pivot_wider

-   ggplot2

    -   map

    -   readers

    -   theme

### Part II - Practicum

#### File Links

-   Education [[Link](https://ds-sl.github.io/intro2r/da4r/education.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/education.Rmd)]

-   Week Four Assignment Template [[Link](https://ds-sl.github.io/intro2r/da4r/w4_assignment_template.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/w4_assignment_template.Rmd)]

#### Week Four Assignment

Choose at least two *similar* WDI codes with the *same scale*, and analyze the data.

-   Create an R Notebook of a data analysis containing the following and submit the rendered file (e.g., `w4_g123456.nb.html`) in Moodle.

    1.  Create an R Notebook using the R Notebook Template in Moodle and save it as `w4_g123456.Rmd`.

    2.  Edit author with name, ID, and title.

<!-- -->

-   Contents should include the following:

    -   A short abstract

    -   Information of data including data name, data code (or id), description

    -   Data including at least two indicators and a long table created using `pivot_longer`

    -   A line graph using the long table with a color aesthetic to depict at least two indicators in a chart.

    -   Several charts: a bar graph or a column graph, a histogram, a line graph, a scatter plot

    -   Observations or questions for visualizations

-   Include a choropleth map, if possible. (a challenge, not required)

-   Run each code block and preview to create `w4_g123456.nb.html`.

    -   Or, Run All under Run and Preview to check in your web browser!

    -   You can also view your file (e.g. `w4_g123456.nb.html`) by opening it from your web browser.

Submit your R Notebook file (w4_g123456.nb.html) in Moodle (Week Four Assignment).

***Due Sunday 21, January 2024, 11:59 PM***

## Week 5 (2024/01/24)

Exploratory Data Analysis IV [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-05.html)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-05.nb.html)], [Video1], [Video2]

### Part I

-   R Environments

-   readr, readxl

    -   CSV and Excel files

-   dplyr

    -   two tables verbs

-   model

-   summary and review

### Part II - Practicum

#### File Links

-   Public Data [[Link](https://ds-sl.github.io/intro2r/da4r/public_data.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/public_data.Rmd)]

-   Week Five Assignment Template [[Link](https://ds-sl.github.io/intro2r/da4r/w5_assignment_template.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/w5_assignment_template.Rmd)]

#### Week Five Assignment

Choose a data from UN data or OECD data.

-   Create an R Notebook of a data analysis containing the following and submit the rendered file (e.g., `w5_g123456.nb.html`) in Moodle.

    1.  Create an R Notebook using the R Notebook Template in Moodle and save it as, for example, `w5_g123456.Rmd`.

    2.  Edit author with name, ID, and title.

-   Contents should include the following:

    -   A short abstract

    -   Information of data including data name, description and link to reach the data

    -   Several charts: a bar graph or a column graph, a histogram, a line graph, a scatter plot

    -   Observations or questions for visualizations

-   Use left_join, if possible. (a challenge, not required)

-   Run each code block and preview to create, for example, `w5_g123456.nb.html`.

    -   Or, Run All under Run and Preview to check in your web browser!

    -   You can also view your file (e.g. `w5_g123456.nb.html`) by opening it from your web browser.

Submit your R Notebook file (w5_g123456.nb.html) in Moodle (Week Five Assignment).

***Due Sunday 28, January 2024, 11:59 PM***

## Week 6 (2024/01/31)

Exploratory Data Analysis V [[Slides](https://ds-sl.github.io/intro2r/da4r/qall401-06.html)], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/qall401-06.nb.html)], [[Video1](https://youtu.be/bgGR_mZ1ox0)], [[Video2](https://youtu.be/wipkINZz8Ko)]

### Part I

-   EDA Workflow
-   Examples of EDA
-   Reproducible Research and Communication
    -   PDF, Word, PowerPoint, Other Slides, etc

### Part II - Practicum

-   For Communication: migrants_note [[Link](https://ds-sl.github.io/intro2r/da4r/migrants_note.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/migrants_note.Rmd)]

-   Week Six Assignment Template [[Link](https://ds-sl.github.io/intro2r/da4r/w6_assignment_template.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/w6_assignment_template.Rmd)]

-   Model: gini_and_inequality [[Link](https://ds-sl.github.io/intro2r/da4r/gini_and_inequality.nb.html)], [[Rmd](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/gini_and_inequality.Rmd)]

### Assignment 5

## Week 7 (2024/02/07)

Professor Taisei Kaizoji

Data Analysis Project 1

## Week 8 (2024/02/14)

Professor Taisei Kaizoji

Data Analysis Project 2

## Week 9 (2024/02/21)

Professor Taisei Kaizoji

Data Analysis Project 3

## Week 10 (2024/02/28)

Student Presentations

## References

1.  Data Analysis for Researchers. [[Link](https://icu-hsuzuki.github.io/da4r/)]

2.  H. Wickham. *R for Data Science (2e)*. [[Link](https://r4ds.hadley.nz)]・[[O'REILLY](https://www.oreilly.com/library/view/r-for-data/9781492097396/)].

    -   Standard Textbook, revised from the first edition in 2023. [[1e](https://r4ds.had.co.nz/)]

3.  Bookdown. [[Link](https://bookdown.org)] [[Archive Link](https://bookdown.org/home/archive/)]

4.  Y. Xie et al. *R Markdown Cookbook.* [[Link](https://bookdown.org/yihui/rmarkdown/)]

5.  Posit Primers.（The Basics, Work with Data, Visualize Data, Tidy Your Data, R Reproducibly. [[Link](https://posit.cloud/learn/primers)]

6.  Cheat Sheet. [[Site Link](https://rstudio.github.io/cheatsheets/)]

7.  Posit Cloud. [[Link](https://posit.cloud)] [[Shared Link](https://posit.cloud/content/5539763)] [[Posit Cloud Guide Link](https://posit.cloud/learn/guide)]
