---
title: "Data Analysis for Researchers 2023, Week 2"
author: "Hiroshi Suzuki"
date: "2023/12/20"
output:
  html_notebook: default
  ioslides_presentation:
    widescreen: yes
  html_document:
    df_print: paged
---

# Part I: R and RStudio

## R, RStudio and Posit Cloud

-   R and RStudio: Install from [[Link](https://posit.co/download/rstudio-desktop/)] and start RStudio

    -   Creating a project, starting with a project

    -   `R.version.string`, Package updates

    -   Installation of Packages

-   Posit Cloud

    -   (Sign Up at [[posit Cloud](https://posit.cloud/)], and save [[Shared Project](https://posit.cloud/content/5539763)] as a permanent copy)

    -   Log In to your Posit Cloud account, and open `intro2rj` project.

    -   Update R version: R 4.3.2

    -   Package updates: Tools \> Check for Package Updates ...

## A short introduction to R

We use an R script

1.  Create an R script from the [Files] tab in the right below pane

2.  Go to the the following [[Link](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/baseR_basics.R)]

3.  Copy and paste the contents by using [Copy raw file] button next to [Raw] on top right.

------------------------------------------------------------------------

### First three or four

The data `iris` is a part of the pre-installed package `datasets.` [[Link](https://en.wikipedia.org/wiki/Iris_flower_data_set)]

-   head(iris): the first 6 rows

-   str(iris): the structure of the object

-   summary(iris): the summary of the object

-   plot(iris\$Petal.Length, iris\$Petal.Width): plot x = iris\$Petal.Length, y = iris\$Petal.Width

------------------------------------------------------------------------

### Assignment and piping

-   df_iris \<- iris: assignment

-   df_iris[c(3,4)] \|\> plot() :plot x = column 3, y = column 4

-   lm(iris\$Petal.Length \~ iris\$Petal.Width, df_iris): the coefficients of the formula of the regression line

-   df_iris \|\> lm(iris\$Petal.Length \~ iris\$Petal.Width, data = \_): same as above

------------------------------------------------------------------------

### Subsetting

-   df_iris[3,4]: the value in the third row, the fourth column

-   df_iris[c(3,4)]: the data table consisting of the third and the fourth columns

-   df_iris[c(3,4,5)]: the data table consisting of the columns three, four and five

-   df_iris[3:5]: same as above, 3:5 returns a sequence from 3 to 4

-   df_iris[[5]] \|\> unique(): distinct entries in the fifth column

-   df_iris\$Species \|\> unique(): same as above

## Gapminder [[Link](https://www.gapminder.org)]

-   Upgrade Your Worldview

-   Dollar Street

-   Animation Charts

    -   Babies per woman vs Life expectancy [[Link](https://www.gapminder.org/tools/#$model$markers$bubble$encoding$x$data$concept=children_per_woman_total_fertility&source=sg&space@=country&=time;;&scale$domain:null&zoomed:null&type:null;;;;;;&chart-type=bubbles&url=v1)]

        -   Total fertility vs Life expectancy at birth

        -   How many variables?

    -   About Data: Fact \> Data [[Link](https://www.gapminder.org/data/)]

## World Development Indicators

### Data themes [[Link](https://datatopics.worldbank.org/world-development-indicators/)]

-   Find data you want to study. Record the name, WDI code, and possibly the URL.

-   People [[Link](https://datatopics.worldbank.org/world-development-indicators/themes/people.html)]

    -   Population, total: SP.POP.TOTL [[Link](https://data.worldbank.org/indicator/SP.POP.TOTL)]

    -   Fertility rate, total (births per woman): SP.DYN.TFRT.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.TFRT.IN)]

    -   Life expectancy at birth, total: SP.DYN.LE00.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)]

# Part II: Practicum

## Life-expectancy

-   R Notebook [[Link](https://github.com/ds-sl/intro2r/blob/main/docs/da4r/life_expectancy.Rmd) to the source], [[R Notebook](https://ds-sl.github.io/intro2r/da4r/life_expectancy.nb.html)]

-   World Development Indicators: life-expectancy

    -   Population, total: SP.POP.TOTL [[Link](https://data.worldbank.org/indicator/SP.POP.TOTL)]

    -   Fertility rate, total (births per woman): SP.DYN.TFRT.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.TFRT.IN)]

    -   Life expectancy at birth, total: SP.DYN.LE00.IN [[Link](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)]

------------------------------------------------------------------------

### Data Importing

-   df_lifeexp \<- WDI(indicator = c(pop = " SP.POP.TOTL", fertility = "SP.DYN.TFRT.IN", lifeexp = "SP.DYN.LE00.IN"), extra = TRUE)

-   WDI: help

    -   WDI(country = "all", indicator = c(pop = " SP.POP.TOTL", fertility = "SP.DYN.TFRT.IN", lifeexp = "SP.DYN.LE00.IN"), start = 1960, end = NULL, extra = TRUE, caches = NULL, latest = NULL, language = "en")

    -   WDI()

------------------------------------------------------------------------

### Data Transforming

-   `dplyr`, a package in tidyverse

    -   `select()` : select columns `select(c(1,2,4,5,7,8))`

    -   `filter()` : select rows meeting a condition

        -   `filter(country == "World")`

        -   `filter(iso2c %in% c("JP", "IN", "CN"))`

        -   `filter(region != "Aggregates")`

    -   `distinct()` : select rows with distinct values of a variable `distinct(country)`

    -   `drop_na()` : drop rows with NA values, e.g. `drop_na(pop)`

------------------------------------------------------------------------

### Data Visualizing

-   ggplot2

    -   `ggplot(aes(x=var1, y=var2))`

    -   Scatter Plot: `geom_point(aes(col=var3, size=var4, shape=var5))`

    -   Line Graph: `geom_line(aes(col=var3, linetype=var4)))`

    -   Title, Subtitle, Legend and Axis labels

        -   `labs(title = "", subtitle ="", x  = "", y = "", col = "")`

## Week Two Assignment

**Self-introduction Plus**

1.  Self-introduction and 'Please call me ... .'

2.  What do you expect from this course?

3.  Write the name and the WDI code of the WDI data you are interested in. Reason?

4.  List the data you want to study and investigate, if any. (Optional)

***Due Sunday 24, December 2023, 11:59 PM***

## Recommended Readings and Activities

1.  World Development Indicators: Data themes [[Link](https://datatopics.worldbank.org/world-development-indicators/)]

    -   Find data you want to study. Record the name, WDI code, and possibly the URL.

2.  Posit Primers - interactive exercises: The Basics [[Link](https://posit.cloud/learn/primers/1)]

    1.  [Visualization Basics](https://posit.cloud/learn/primers/1.1)

    2.  [Programming Basics](https://posit.cloud/learn/primers/1.2)

3.  RStudio IDE Cheat Sheet. PDF is available on the top right. [[Site Link](https://rstudio.github.io/cheatsheets/html/rstudio-ide.html)]
