---
title: "QALL401 Data Analysis for Researchers - Students' Contributions"
author: "Hiroshi Suzuki"
output: 
  html_notebook: 
    toc: true
---

# Members

- NAME_E	NAME_KJ	DIVISION	EMAIL	Nickname
- c241183: KISHI, MAYU 	岸 真由	5年プログラム	c241183a@icu.ac.jp	Mayu, or Kishimayu
- c241338: OOKA, AKI 	大岡 亜樹	5年プログラム	c241338k@icu.ac.jp	Aki
- c241429: TAGAWA, MIO 	田川 美桜	5年プログラム	c241429r@icu.ac.jp	Mio
- c241456: TAMAGAWA, KAI 	玉川 海	5年プログラム	c241456w@icu.ac.jp	Kai
- c241527: YANG, PEIQING 	楊 佩青	5年プログラム	c241527r@icu.ac.jp	Penny
- c241554: RAO, SHUNYU 		5年プログラム	c241554w@icu.ac.jp	Aria
- c241559: ZHENG, WENBO 	鄭 文博	5年プログラム	c241559t@icu.ac.jp	Alan
- c241786: VIRTUDAZO, ETHAN JOSAFAT ARNUEVO		AS (ECO)	c241786t@icu.ac.jp	
- g245701: LIN, CHING-TING			g245701n@icu.ac.jp	Ting
- g245702: TUANO, CHRISANNE MORAL			g245702s@icu.ac.jp	Kris
- g246704: DE VERA, DARA ABEGAIL MAMINTA			g246704n@icu.ac.jp	Dara
- g246705: MURPHY, THOMAS JAMES			g246705s@icu.ac.jp	Tom
- g246715: SAKAI, GAKU	酒井 岳		g246715x@icu.ac.jp	Gaku
- g246717: SHIRAI, YOUSUKE	白井 葉介		g246717k@icu.ac.jp	-
- g246719: AL-HAMATI, ANAS ALI SALEH			g246719s@icu.ac.jp	Ali
- g256004: FURUSAWA, RINA	古澤 里菜		g256004n@icu.ac.jp	Rina, Rina-san, or Furusawa-san
- g256005: YANAGIDA, TAKAKI	柳田 尭紀		g256005s@icu.ac.jp	Takaki
- g256009: SUN, YIDI			g256009m@icu.ac.jp	Yidi
- g256019: HANADA, HIROKI	花田 浩紀		g256019s@icu.ac.jp	Hiroki
- g256020: HIRAI, SHU  	平井 秀		g256020k@icu.ac.jp	Shu
- g256021: NAKAGAWA, TOMOYA  	中川 知弥		g256021n@icu.ac.jp	Nakagawa-san
- g256709: FERNANDO, MANDADIGE KASUN UDARA SAMPATH			g256709x@icu.ac.jp	Kasun
- g256710: NGUYEN, THI VIET LINH			g256710r@icu.ac.jp	Linh
- g256711: SUN, XIAOXUAN			g256711t@icu.ac.jp	Xiaoxuan
- g256712: UDATIYAWALA ARACHCHIGE , CHAMILANI			g256712x@icu.ac.jp	Chamilani
- g256717: MC NEVIN, NICOLE JOY			g256717w@icu.ac.jp	Nicole
- g256724: WRIGHT, MAXWELL ALEXANDER WING CHEONG			g256724r@icu.ac.jp	Max

# Projects

- NAME_E	NAME_KJ	DIVISION	EMAIL	Nickname
- c241183: KISHI, MAYU:  fertility, OECD
  - https://stats.oecd.org/Index.aspx?QueryId=20505
- c241338: OOKA, AKI: palm oil production and harvest areas, UN, WB, owid
- c241429: TAGAWA, MIO: wage, education spending, OECD
- c241456: TAMAGAWA, KAI
- c241527: YANG, PEIQING: long-term interest rate OECD, cip etc
- c241554: RAO, SHUNYU: Gender Equality and Birth Rate, Considering Economic Factors, WDI
- c241559: ZHENG, WENBO: GDP Per Capita and Savings Rate, WDI
- c241786: VIRTUDAZO, ETHAN JOSAFAT ARNUEVO: Bank Runs (OR: Case Study Analysis of Silicon Valley Bank Collapse), Alpha Vantage
- g245701: LIN, CHING-TING: Fear of failure and Parenting Styles, personally collected
- g245702: TUANO, CHRISANNE MORAL: Gender Roles, Domestic Violence, and Early Marriage, WDI
- g246704: DE VERA, DARA ABEGAIL MAMINTA: Competencies with Employee Performance of Two Government Corporations in the Philippines
- g246705: MURPHY, THOMAS JAMES: Closing Digital Divide, data collected and WDI
- g246715: SAKAI, GAKU: Kaggle; titled as “1.3M LinkedIn Jobs & Skills (2024)
- g246717: SHIRAI, YOUSUKE: The Japanese Listed Companyʼs Board Member Composition by gender.
- g246719: AL-HAMATI, ANAS ALI SALEH: Population and GDP Growth in Pakistan, WDI
- g256004: FURUSAWA, RINA: GDP, Agricultural land and CO2 emissions, WDI
- g256005: YANAGIDA, TAKAKI: 
- g256009: SUN, YIDI: Comparative Analysis of Economic Performance: The Trump Administration vs. the Final Years of the Obama Presidency, WDI
- g256019: HANADA, HIROKI: Request Rate and Performance of Web Servers with Different Backends, data generation
- g256020: HIRAI, SHU: Japan's Technology Industry in Data, WDI?
- g256021: NAKAGAWA, TOMOYA: 各国の半導体自給率と安全保障, in search
- g256709: FERNANDO, MANDADIGE KASUN UDARA SAMPATH: Casual Relationship in labor productivity with foreign direct investments. , WDI
- g256710: NGUYEN, THI VIET LINH: foreign direct investment (FDI) from the United States (US) into OECD countries, OECD
- g256711: SUN, XIAOXUAN: Industrial Freshwater Withdrawals on Agricultural Land Use, WDI
- g256712: UDATIYAWALA ARACHCHIGE , CHAMILANI: Impact of Worker Remittances on Economic Growth., data?
- g256717: MC NEVIN, NICOLE JOY: Top Countries for Study Abroad and Their Attributes, Kaggle
- g256724: WRIGHT, MAXWELL ALEXANDER WING CHEONG: Trends in global fertilizer consumption and impacts on agricultural nitrous oxide emissions and agricultural production, WDI


# Presentations

- NAME_E	NAME_KJ	DIVISION	EMAIL
- 4:40 g256020: HIRAI, SHU 
  - Modern Japanese Exports: three questions: WDI high technology exprorts
  - Number of technicians: Jpan's indices are declining
- 4:40 c241786: VIRTUDAZO, ETHAN JOSAFAT ARNUEVO
  - Popularity of article? lenght
  - Article Lenght 548, Word Lenght 4.55, Entermaint: 529.5, Word lenght 4.6
- 4:45 g245701: LIN, CHING-TING
  - Issue of fear of failure among students
  - parenting style and FF
  - comparison of models
- 4:50 g245702: TUANO, CHRISANNE MORAL
  - Domestic violence, early marrage, young age pregnancy
  - belief that thre is justfied VAW, violence againct wives, across region
  - Sub-Saharan Africa and South Asia: rates of both early marriage and justification of VAW
  - correlation matrix
- 4:55 g246704: DE VERA, DARA ABEGAIL MAMINTA
  - Relationship between Competencies and Employee Performance
  - Educagion distribution, Employeee performaince by Education level
  - Competency assessment across years
- 5:00 g246705: MURPHY, THOMAS JAMES
  - Digital divide in East Asia and {acofoc}
  - Choropleth map
- 5:05 g246715: SAKAI, GAKU
  - LinkedIn Job Posts in the US *2023): 6 experience level: better to use factor
- 5:10 g246717: SHIRAI, YOUSUKE
  - Gender Inequality in Japanese Company
  - Independent women pct, Internal women pct
  - Percentage of women emplyees
- 5:15 g246719: AL-HAMATI, ANAS ALI SALEH - sick
  - Population growth rate, and GDP growth in Pakistan: needs balance
- 5:20 g256004: FURUSAWA, RINA
  - Voicing Contrast in Singing, ta vs da, sa vs da, 
  - In singing voicing, VOT in singing and speech, vcd, vs vcl (voice less)
- 5:25 g256005: YANAGIDA, TAKAKI
  - Eploratory analysis of baseball: pichers' performance
  - https://baseballsavant.mlb.com/statcast_search
  - release points vs K/BB
- 5:30 g256009: SUN, YIDI
  - Trump vs Obama, GDP, Fiscal Deficet, Debt, Inflation, Unemployment, Infrastructure Investment
- 5:35 g256019: HANADA, HIROKI
  - EDA on Performance Metrics of the Emulated and Original Microeservices Benchmark
  - end to end latency

- Break
- 5:45 c241338: OOKA, AKI 
  - Palm oil, land area: How did palm oil pruduction increase
  - geom_area can be used, scale log10
- 5:55 g256021: NAKAGAWA, TOMOYA
  - Prediction of World semiconductor sales trend using linear regression and digital fourier Transform
  - Upward trend, small oscillation (Si Cycle)
  - Parametric and non parametric approach
- 6:00 g256709: FERNANDO, MANDADIGE KASUN UDARA SAMPATH
  - How does India achieve economic stability? : foreign direct investment
- 6:05 g256710: NGUYEN, THI VIET LINH
  - Determinants Flugszfc FDI by US to OECD
- 6:10 g256711: SUN, XIAOXUAN
  - Impact of agrricautural land, industry,  and water
- 6:15 g256712: UDATIYAWALA ARACHCHIGE, CHAMILANI
  - Impact of; remittances, imports, fpreogm direct investment
  - foreign remittances on economic growth
- 6:20 g256717: MC NEVIN, NICOLE JOY
  - International Studdent Mobility: EDA
  - to sending nations and receiveing nations
  - Kaggle, Inbound student mobility, outbound student mobility from UNESCO [[Link](http://data.uis.unesco.org/index.aspx?queryid=3807)]
  - Name label
- 6:25 g256724: WRIGHT, MAXWELL ALEXANDER WING CHEONG
  - how agriculture impacte greenhouse emissions using WDI
  - Agriculture land vs emissions: log10 scale
  - Fertiizer and Nitrous Oxide, Faroe island
- 6:30 c241183: KISHI, MAYU
  - The relationship between fertility rate and gender wage gap (OECD)
  - France, Iceland, Japan, South Korea, explanaton of D1 and D9
- 6:35 c241429: TAGAWA, MIO
  - Current situation of renewable energy consumption
  - long title, isoslides use
  - Renewable energy consumption, low income countries, and regions, choropleth maps
- 6:40 c241456: TAMAGAWA, KAI
  - **[NO: did not show-up]**
- 6:45 c241527: YANG, PEIQING
  - long term interest rate of the U.S. and Japan: OECD, Yahoo finance
  - Long and short term interest rate: OECD, VIX frmm hayhoo finance, Nikkei stock average
- 6:50 c241554: RAO, SHUNYU 
  - gender equality and birth rate, considering economic factors, GNI (PPP), GINI, School Enrolment, Seats of parliaments, birth rate, 
  - Psychology,  oofplog…… offplogmixed
- 6:55 c241559: ZHENG, WENBO
  - Saving rate: Gross savings, GDP p cap, CPI, unemployment
  - GDP per Capita vs Saving rate

- Final Remark

  - Line break in the title and use of subtitle
  - APA table:Create American Psychological Association (APA) Style Tables [Link](https://cran.r-project.org/web/packages/apaTables/index.html) (Rao)
  - Mac Connection: Command F1, Command FN, F1


# Paper

- NAME_E	NAME_KJ	DIVISION	EMAIL	Nickname
- c241183: KISHI, MAYU
- c241429: OOKA, AKI
- c241429: TAGAWA, MIO
- c241456: TAMAGAWA, KAI
- c241527: YANG, PEIQING
- c241554: RAO, SHUNYU 
- c241559: ZHENG, WENBO
- c241786: VIRTUDAZO, ETHAN JOSAFAT ARNUEVO	
- g245701: LIN, CHING-TING
- g245702: TUANO, CHRISANNE MORAL
- g246704: DE VERA, DARA ABEGAIL MAMINTA
- g246705: MURPHY, THOMAS JAMES
- g246715: SAKAI, GAKU
- g246717: SHIRAI, YOUSUKE
- g246719: AL-HAMATI, ANAS ALI SALEH
- g256004: FURUSAWA, RINA
- g256005: YANAGIDA, TAKAKI
- g256009: SUN, YIDI
- g256019: HANADA, HIROKI
- g256020: HIRAI, SHU 
- g256021: NAKAGAWA, TOMOYA
- g256709: FERNANDO, MANDADIGE KASUN UDARA SAMPATH
- g256710: NGUYEN, THI VIET LINH
- g256711: SUN, XIAOXUAN
- g256712: UDATIYAWALA ARACHCHIGE , CHAMILANI
- g256717: MC NEVIN, NICOLE JOY
- g256724: WRIGHT, MAXWELL ALEXANDER WING CHEONG