---
title: "生涯学び続ける基盤を構築する<br>データサイエンス・コースの開発"
author: "鈴木 寛（Hiroshi Suzuki）"
date: 'Last Updated: `r Sys.Date()`'
output:
  html_notebook:
    toc: yes
    toc_float: yes
    highlight: tango
    theme: cerulean
    number_sections: yes
  ioslides_presentation: 
    highlight: tango
    widescreen: yes
    smaller: yes
    fig_height: 3.5
    fig_retina: 1
  pdf_document:
    latex_engine: xelatex
  slidy_presentation:
    highlight: tango
header-includes: \usepackage{ctex}
---

# データサイエンス・コースの開発

## コースの提案

レベル：リテラシーレベルを二段階に設定して設計

内容：基本的に下の二つとし、それを融合させた形で行う。

1. AI（人工知能）との付き合い方を学ぶ
2. 世界や、ひとびとの課題について、データサイエンスで学ぶ

形式：グループワーク

1. 少人数で、調べることと共に、問いを精査する場面で協力を促す
2. グループの一員として、AI を活用する

対象：分野横断型の受講生の構成が望ましい


# データサイエンス・コースの開発<br>レベル１

## 第一レベル

1. AI に触れる：Duolingo、ChatGPT など
2. WDI: 日本に関するデータ - ダッシュボード
3. WDI: 指標を選択して、課題と向き合う
    - 自分達の興味のあるデータを調べる
    - 問題意識をしっかり持てるようにする
    - データに基づいた思考ができるようにする
    - 批判的思考、バイアスを意識しながら
    - 他者と協力、分担して、調べ、ディスカッション
4. AI の基本を学ぶ
5. AI との付き合い方についての、ディスカッション
6. トピックを決めてグループ発表

  
学生のレベルによっては、第二レベルから始めても良い

## AI を使ってみる：語学学習アプリ Duolingo

携帯電話など（App Store、Google Play で取得）で利用することが一般的だが、PCでも利用可能。

世界で、４億人以上が使った経験を持っているといわれ、300万人以上が、１年間以上継続していると報じられている。読み・書き・聞き・話すの四技能。

- Duolingo を使ってみる。二週間ほど。
  - 継続するために、どのような方法が考えられているか。
  - なぜ、Follow や、Followed by のような仲間を作ることを奨励しているのか。
  - 仲間とのやりとりはどのように制限されているか。
  - 課金のためには、どのような方法が取られているか。
  - 採点には、どのような手法が取られているか。
  - AI が使われているのは、どのような部分だと思われるか。
  - 気に入った点、気に入らない点、すばらしいと思えること、改善が必要だと思うこと。
  
**Mission: We’re here to develop the best education in the world and make it universally available.**　
  

## AI を使ってみる：Chat GPT

- どのようなことに、AI は使われていくだろうか。
  - 有効と思われるものを挙げてみよう。
  - 問題、課題がある使われ方を挙げてみよう。
  - 不安を感じることはどのようなことだろうか。
  
- どのように、付き合って行ったら良いだろうか。
- 目的は、さまざまな情報に対して、批判的思考を訓練しながら、より適切に、学ぶスキルを向上させること。
- ちょっと変わった新来者にどう対応するかを考え、経験する

## 日本から世界を見る

以下では、世界銀行の、世界開発指標を利用する。

他にも、活用できるサイトがいくつかある。

* 国際連合　[UNdata](https://data.un.org)
* 経済協力開発機構　[OECD data](https://data.oecd.org)、
* 世界格差データベース（World Inequality Database）[WID](https://wid.world)、
* 欧州連合の統計局　[Eurostat](https://ec.europa.eu/eurostat)、
* データで見る私たちの世界　[Our World in Data](https://ourworldindata.org)

なども、同様の、ダッシュボードを備えており、データの提供もしている。

<p>
日本では、

* [e-Stat](https://www.e-stat.go.jp/)、
* [ダッシュボード](https://dashboard.e-stat.go.jp)

## 持続的開発目標（SDGs） データ

* 世界銀行：https://databank.worldbank.org/source/sustainable-development-goals-(sdgs)
* 国連：https://unstats.un.org/sdgs/dataportal/database
* データで見る私たちの世界：Our World in Data SGD Tracker: https://sdg-tracker.org/
* SDG Index: https://dashboards.sdgindex.org/map


## World Bank: WDI - World Development Indicaters

* 世界銀行（World Bank）: https://www.worldbank.org
* [世界銀行について（Who we are）](https://www.worldbank.org/en/who-we-are):
  - 極度の貧困状態の削減（To end extreme poverty）: 2030年までに、極度の貧困状態にある世界人口の割合を3%に削減する。By reducing the share of the global population that lives in extreme poverty to 3 percent by 2030.
  - 繁栄を共に享受（To promote shared prosperity）: すべての国の最貧困層の40％の人々の所得を増加させることによって共栄を促進。By increasing the incomes of the poorest 40 percent of people in every country. 
* 世界銀行オープンデータ（World Bank Open Data）: https://data.worldbank.org
  - Data Bank, World Development Indicators, etc.
  
日本について：https://data.worldbank.org/country/japan?view=chart

## 世界開発指標（WDI）

* [World Development Indicators (WDI)](https://datatopics.worldbank.org/world-development-indicators/) : 世界銀行が開発に関する各国間比較可能なデータの集大成である1400の時系列指標（the World Bank’s premier compilation of cross-country comparable data on development; 1400 time series indicators）
  - テーマ別（Themes）: 貧困と格差、人間、環境、経済、国家と市場、グローバルリンク集（Poverty and Inequality, People, Environment, Economy, States and Markets, Global Links）
  - オープンデータとデータバンク（Open Data & DataBank）: Explore data, Query database
  - Bulk Download: Excel, CSV
  - API Documentation

## 例
### 一人当たりのGDP(定数2015米ドル)：[リンク](https://data.worldbank.org/indicator/NY.GDP.PCAP.KD?locations=JP-GB-RU-FR-CN-US-UA-DE&start=2021&end=2021&view=bar)
  

実質GDP（2015年を基準にしたもの）を、総人口で割った値。

<!-- アメリカ合衆国、英国、ドイツ、フランス、日本、中国、日本、ロシア、ウクライナの2021年における比較棒グラフ  -->


<!-- <iframe src="https://data.worldbank.org/share/widget?end=2021&indicators=NY.GDP.PCAP.KD&locations=JP-GB-RU-FR-CN-US-UA-DE&start=2021&view=bar" width='300' height='150' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## 年次変化を示す折線グラフ -  -->

<!-- <iframe src="https://data.worldbank.org/share/widget?end=2021&indicators=NY.GDP.PCAP.KD&locations=JP-GB-RU-FR-CN-US-UA-DE&start=1960&view=chart" width='300' height='150' frameBorder='0' scrolling="no" ></iframe> -->


### 2020年の政府の負債（GDP の百分率）：[リンク](https://data.worldbank.org/indicator/GC.DOD.TOTL.GD.ZS?locations=JP-GB-RU-FR-CN-US-UA-DE&start=2020&end=2020&view=bar)

<!-- 日本、イギリス、ロシア連邦、フランス、中国、米国、ウクライナ、ドイツ -->



<!-- <iframe src="https://data.worldbank.org/share/widget?end=2020&indicators=GC.DOD.TOTL.GD.ZS&locations=JP-GB-RU-FR-CN-US-UA-DE&start=2020&view=bar" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## 例：政府の負債（GDP の百分率）の年次変化を示す折線グラフ -->

<!-- <iframe src="https://data.worldbank.org/share/widget?indicators=GC.DOD.TOTL.GD.ZS&locations=JP-GB-RU-FR-CN-US-UA-DE" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


### CO2 排出量 (1 人あたりのメートル トン) ：[リンク](https://data.worldbank.org/indicator/EN.ATM.CO2E.PC?locations=JP-GB-RU-FR-CN-US-UA-DE&start=2019&end=2019&view=bar)


<!-- 日本、イギリス、ロシア連邦、フランス、中国、米国、ウクライナ、ドイツ -->


<!-- <iframe src="https://data.worldbank.org/share/widget?end=2019&indicators=EN.ATM.CO2E.PC&locations=JP-GB-RU-FR-CN-US-UA-DE&start=2019&view=bar" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## CO2 排出量 (1 人あたりのメートル トン) の年次変化の折線グラフ -->

<!-- <iframe src="https://data.worldbank.org/share/widget?end=2019&indicators=EN.ATM.CO2E.PC&locations=JP-GB-RU-FR-CN-US-UA-DE&start=1990&view=chart" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


### 2021年の軍事費 (GDP の %) ： [リンク](https://data.worldbank.org/indicator/MS.MIL.XPND.GD.ZS?locations=JP-GB-RU-FR-CN-UA&start=2021&end=2021&view=bar)


<!-- 日本、イギリス、ロシア連邦、フランス、中国、ウクライナ -->


<!-- <iframe src="https://data.worldbank.org/share/widget?end=2021&indicators=MS.MIL.XPND.GD.ZS&locations=JP-GB-RU-FR-CN-UA&start=2021&view=bar" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## 軍事費 (GDP の %) の年次変化 -->

<!-- <iframe src="https://data.worldbank.org/share/widget?indicators=MS.MIL.XPND.GD.ZS&locations=JP-GB-RU-FR-UA-KR-DE&view=chart" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


### 2021年の軍事費 (現在の米ドル) ： [リンク](https://data.worldbank.org/indicator/MS.MIL.XPND.CD?locations=JP-GB-RU-FR-CN-UA&start=2021&end=2021&view=bar)
 

<!-- 日本、イギリス、ロシア連邦、フランス、中国、ウクライナ -->


<!-- <iframe src="https://data.worldbank.org/share/widget?end=2021&indicators=MS.MIL.XPND.CD&locations=JP-GB-RU-FR-CN-UA&start=2021&view=bar" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## 軍事費の年次変化 -->

<!-- <iframe src="https://data.worldbank.org/share/widget?indicators=MS.MIL.XPND.CD&locations=JP-GB-RU-FR-UA-KR-DE&view=chart" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


### 2021年、国会で女性が占める議席の割合 (%)：[リンク](https://data.worldbank.org/indicator/SG.GEN.PARL.ZS?locations=JP-GB-RU-FR-CN-US-UA-DE&start=2021&end=2021&view=bar)


<!-- 日本、イギリス、ロシア連邦、フランス、中国、米国、ウクライナ、ドイツ -->


<!-- <iframe src="https://data.worldbank.org/share/widget?end=2021&indicators=SG.GEN.PARL.ZS&locations=JP-GB-RU-FR-CN-US-UA-DE&start=2021&view=bar" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->


<!-- ## 国会で女性が占める議席の割合 (%) の年次変化 -->

<!-- <iframe src="https://data.worldbank.org/share/widget?indicators=SG.GEN.PARL.ZS&locations=JP-GB-RU-FR-CN-US-UA-DE" width='450' height='300' frameBorder='0' scrolling="no" ></iframe> -->

## 世界のさまざまな課題

https://datatopics.worldbank.org/world-development-indicators/

1. 貧困と不平等（Poverty and Inequality）：貧困、繁栄、消費、所得分配
2. 人々（People）：人口動態、教育、労働、健康、ジェンダー
3. 環境（Environment）：農業、気候変動、エネルギー、生物多様性、水、衛生
4. 経済（Economy）：成長、経済構造、所得と貯蓄、貿易、労働生産性
5. 国家と市場（States and Markets）：ビジネス、株式市場、軍事、通信、輸送、テクノロジー
6. グローバルリンク（Global Links）：債務、貿易、援助への依存、難民、観光、移住

# データサイエンス・コースの開発<br>レベル2

## 第二レベル

1. AI と データサイエンスについてのディスカッション
2. PositCloud 入門、スクリプトの利用
3. R Notebook 入門
4. WDI パッケージの利用
5. テンプレートの利用
6. tidyverse の基本の学び
7. 可視化の学び
8. WDI 以外のデータの取得
9. プロジェクト
10. 発表

<p>
コンピュータ言語 R を推奨する理由：無償、インタラクティブ、プログラミングの経験がなくても使える、発展性に富み、十分な利用者がおり、教材が多い

## Posit Cloud による実習

資料へのリンク

<center><font size="10">https://bit.ly/rims2023</font></center>
<center><font size="10">　</font></center>

[R ではじめるデータサイエンス](https://ds-sl.github.io/intro2r/intro2rj.nb.html)

<center><font size="10">https://posit.cloud/content/5539763</font></center>



